// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: lumen/release/v1/bundle.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "lumen.release.v1";

export interface Bundle {
  id: number;
  index: string;
  version: string;
  os: string;
  arch: string;
  cid: string;
  sha256: string;
  sizeBytes: number;
  createdAtUnix: number;
  creator: string;
}

function createBaseBundle(): Bundle {
  return {
    id: 0,
    index: "",
    version: "",
    os: "",
    arch: "",
    cid: "",
    sha256: "",
    sizeBytes: 0,
    createdAtUnix: 0,
    creator: "",
  };
}

export const Bundle: MessageFns<Bundle> = {
  encode(message: Bundle, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.index !== "") {
      writer.uint32(18).string(message.index);
    }
    if (message.version !== "") {
      writer.uint32(26).string(message.version);
    }
    if (message.os !== "") {
      writer.uint32(34).string(message.os);
    }
    if (message.arch !== "") {
      writer.uint32(42).string(message.arch);
    }
    if (message.cid !== "") {
      writer.uint32(50).string(message.cid);
    }
    if (message.sha256 !== "") {
      writer.uint32(58).string(message.sha256);
    }
    if (message.sizeBytes !== 0) {
      writer.uint32(64).uint64(message.sizeBytes);
    }
    if (message.createdAtUnix !== 0) {
      writer.uint32(72).uint64(message.createdAtUnix);
    }
    if (message.creator !== "") {
      writer.uint32(82).string(message.creator);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Bundle {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBundle();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.index = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.version = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.os = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.arch = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.cid = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.sha256 = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.sizeBytes = longToNumber(reader.uint64());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.createdAtUnix = longToNumber(reader.uint64());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Bundle {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      index: isSet(object.index) ? globalThis.String(object.index) : "",
      version: isSet(object.version) ? globalThis.String(object.version) : "",
      os: isSet(object.os) ? globalThis.String(object.os) : "",
      arch: isSet(object.arch) ? globalThis.String(object.arch) : "",
      cid: isSet(object.cid) ? globalThis.String(object.cid) : "",
      sha256: isSet(object.sha256)
        ? globalThis.String(object.sha256)
        : isSet(object.sha_256)
        ? globalThis.String(object.sha_256)
        : "",
      sizeBytes: isSet(object.sizeBytes)
        ? globalThis.Number(object.sizeBytes)
        : isSet(object.size_bytes)
        ? globalThis.Number(object.size_bytes)
        : 0,
      createdAtUnix: isSet(object.createdAtUnix)
        ? globalThis.Number(object.createdAtUnix)
        : isSet(object.created_at_unix)
        ? globalThis.Number(object.created_at_unix)
        : 0,
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
    };
  },

  toJSON(message: Bundle): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.index !== "") {
      obj.index = message.index;
    }
    if (message.version !== "") {
      obj.version = message.version;
    }
    if (message.os !== "") {
      obj.os = message.os;
    }
    if (message.arch !== "") {
      obj.arch = message.arch;
    }
    if (message.cid !== "") {
      obj.cid = message.cid;
    }
    if (message.sha256 !== "") {
      obj.sha256 = message.sha256;
    }
    if (message.sizeBytes !== 0) {
      obj.sizeBytes = Math.round(message.sizeBytes);
    }
    if (message.createdAtUnix !== 0) {
      obj.createdAtUnix = Math.round(message.createdAtUnix);
    }
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Bundle>, I>>(base?: I): Bundle {
    return Bundle.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Bundle>, I>>(object: I): Bundle {
    const message = createBaseBundle();
    message.id = object.id ?? 0;
    message.index = object.index ?? "";
    message.version = object.version ?? "";
    message.os = object.os ?? "";
    message.arch = object.arch ?? "";
    message.cid = object.cid ?? "";
    message.sha256 = object.sha256 ?? "";
    message.sizeBytes = object.sizeBytes ?? 0;
    message.createdAtUnix = object.createdAtUnix ?? 0;
    message.creator = object.creator ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
