// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: lumen/release/v1/params.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "lumen.release.v1";

export interface Params {
  /** bech32 authorized */
  allowedPublishers: string[];
  /** allowed channels */
  channels: string[];
  maxArtifacts: number;
  maxUrlsPerArt: number;
  maxSigsPerArt: number;
  maxNotesLen: number;
  /** escrowed on publish */
  publishFeeUlmn: number;
  /** seconds until pending expires */
  maxPendingTtl: number;
  /** accounts allowed to set emergency_ok */
  daoPublishers: string[];
  /** refund percent on reject (0..10000) */
  rejectRefundBps: number;
  /** stable must be VALIDATED */
  requireValidationForStable: boolean;
}

function createBaseParams(): Params {
  return {
    allowedPublishers: [],
    channels: [],
    maxArtifacts: 0,
    maxUrlsPerArt: 0,
    maxSigsPerArt: 0,
    maxNotesLen: 0,
    publishFeeUlmn: 0,
    maxPendingTtl: 0,
    daoPublishers: [],
    rejectRefundBps: 0,
    requireValidationForStable: false,
  };
}

export const Params: MessageFns<Params> = {
  encode(message: Params, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.allowedPublishers) {
      writer.uint32(10).string(v!);
    }
    for (const v of message.channels) {
      writer.uint32(18).string(v!);
    }
    if (message.maxArtifacts !== 0) {
      writer.uint32(24).uint32(message.maxArtifacts);
    }
    if (message.maxUrlsPerArt !== 0) {
      writer.uint32(32).uint32(message.maxUrlsPerArt);
    }
    if (message.maxSigsPerArt !== 0) {
      writer.uint32(40).uint32(message.maxSigsPerArt);
    }
    if (message.maxNotesLen !== 0) {
      writer.uint32(48).uint32(message.maxNotesLen);
    }
    if (message.publishFeeUlmn !== 0) {
      writer.uint32(56).uint64(message.publishFeeUlmn);
    }
    if (message.maxPendingTtl !== 0) {
      writer.uint32(64).uint64(message.maxPendingTtl);
    }
    for (const v of message.daoPublishers) {
      writer.uint32(74).string(v!);
    }
    if (message.rejectRefundBps !== 0) {
      writer.uint32(80).uint32(message.rejectRefundBps);
    }
    if (message.requireValidationForStable !== false) {
      writer.uint32(88).bool(message.requireValidationForStable);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Params {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.allowedPublishers.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.channels.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.maxArtifacts = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.maxUrlsPerArt = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.maxSigsPerArt = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.maxNotesLen = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.publishFeeUlmn = longToNumber(reader.uint64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.maxPendingTtl = longToNumber(reader.uint64());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.daoPublishers.push(reader.string());
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.rejectRefundBps = reader.uint32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.requireValidationForStable = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      allowedPublishers: globalThis.Array.isArray(object?.allowedPublishers)
        ? object.allowedPublishers.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.allowed_publishers)
        ? object.allowed_publishers.map((e: any) => globalThis.String(e))
        : [],
      channels: globalThis.Array.isArray(object?.channels) ? object.channels.map((e: any) => globalThis.String(e)) : [],
      maxArtifacts: isSet(object.maxArtifacts)
        ? globalThis.Number(object.maxArtifacts)
        : isSet(object.max_artifacts)
        ? globalThis.Number(object.max_artifacts)
        : 0,
      maxUrlsPerArt: isSet(object.maxUrlsPerArt)
        ? globalThis.Number(object.maxUrlsPerArt)
        : isSet(object.max_urls_per_art)
        ? globalThis.Number(object.max_urls_per_art)
        : 0,
      maxSigsPerArt: isSet(object.maxSigsPerArt)
        ? globalThis.Number(object.maxSigsPerArt)
        : isSet(object.max_sigs_per_art)
        ? globalThis.Number(object.max_sigs_per_art)
        : 0,
      maxNotesLen: isSet(object.maxNotesLen)
        ? globalThis.Number(object.maxNotesLen)
        : isSet(object.max_notes_len)
        ? globalThis.Number(object.max_notes_len)
        : 0,
      publishFeeUlmn: isSet(object.publishFeeUlmn)
        ? globalThis.Number(object.publishFeeUlmn)
        : isSet(object.publish_fee_ulmn)
        ? globalThis.Number(object.publish_fee_ulmn)
        : 0,
      maxPendingTtl: isSet(object.maxPendingTtl)
        ? globalThis.Number(object.maxPendingTtl)
        : isSet(object.max_pending_ttl)
        ? globalThis.Number(object.max_pending_ttl)
        : 0,
      daoPublishers: globalThis.Array.isArray(object?.daoPublishers)
        ? object.daoPublishers.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.dao_publishers)
        ? object.dao_publishers.map((e: any) => globalThis.String(e))
        : [],
      rejectRefundBps: isSet(object.rejectRefundBps)
        ? globalThis.Number(object.rejectRefundBps)
        : isSet(object.reject_refund_bps)
        ? globalThis.Number(object.reject_refund_bps)
        : 0,
      requireValidationForStable: isSet(object.requireValidationForStable)
        ? globalThis.Boolean(object.requireValidationForStable)
        : isSet(object.require_validation_for_stable)
        ? globalThis.Boolean(object.require_validation_for_stable)
        : false,
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (message.allowedPublishers?.length) {
      obj.allowedPublishers = message.allowedPublishers;
    }
    if (message.channels?.length) {
      obj.channels = message.channels;
    }
    if (message.maxArtifacts !== 0) {
      obj.maxArtifacts = Math.round(message.maxArtifacts);
    }
    if (message.maxUrlsPerArt !== 0) {
      obj.maxUrlsPerArt = Math.round(message.maxUrlsPerArt);
    }
    if (message.maxSigsPerArt !== 0) {
      obj.maxSigsPerArt = Math.round(message.maxSigsPerArt);
    }
    if (message.maxNotesLen !== 0) {
      obj.maxNotesLen = Math.round(message.maxNotesLen);
    }
    if (message.publishFeeUlmn !== 0) {
      obj.publishFeeUlmn = Math.round(message.publishFeeUlmn);
    }
    if (message.maxPendingTtl !== 0) {
      obj.maxPendingTtl = Math.round(message.maxPendingTtl);
    }
    if (message.daoPublishers?.length) {
      obj.daoPublishers = message.daoPublishers;
    }
    if (message.rejectRefundBps !== 0) {
      obj.rejectRefundBps = Math.round(message.rejectRefundBps);
    }
    if (message.requireValidationForStable !== false) {
      obj.requireValidationForStable = message.requireValidationForStable;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Params>, I>>(base?: I): Params {
    return Params.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Params>, I>>(object: I): Params {
    const message = createBaseParams();
    message.allowedPublishers = object.allowedPublishers?.map((e) => e) || [];
    message.channels = object.channels?.map((e) => e) || [];
    message.maxArtifacts = object.maxArtifacts ?? 0;
    message.maxUrlsPerArt = object.maxUrlsPerArt ?? 0;
    message.maxSigsPerArt = object.maxSigsPerArt ?? 0;
    message.maxNotesLen = object.maxNotesLen ?? 0;
    message.publishFeeUlmn = object.publishFeeUlmn ?? 0;
    message.maxPendingTtl = object.maxPendingTtl ?? 0;
    message.daoPublishers = object.daoPublishers?.map((e) => e) || [];
    message.rejectRefundBps = object.rejectRefundBps ?? 0;
    message.requireValidationForStable = object.requireValidationForStable ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
