// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: lumen/release/v1/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";
import { Release } from "./types";

export const protobufPackage = "lumen.release.v1";

export interface QueryParamsRequest {
}

export interface QueryParamsResponse {
  params: Params | undefined;
}

export interface QueryReleaseRequest {
  id: number;
}

export interface QueryReleaseByIDRequest {
  id: number;
}

export interface QueryReleaseResponse {
  release: Release | undefined;
}

export interface QueryReleasesRequest {
  page: number;
  limit: number;
}

export interface QueryReleasesResponse {
  releases: Release[];
  total: number;
}

export interface QueryLatestRequest {
  channel: string;
  platform: string;
  kind: string;
}

export interface QueryByVersionRequest {
  version: string;
}

function createBaseQueryParamsRequest(): QueryParamsRequest {
  return {};
}

export const QueryParamsRequest: MessageFns<QueryParamsRequest> = {
  encode(_: QueryParamsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryParamsRequest {
    return {};
  },

  toJSON(_: QueryParamsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(base?: I): QueryParamsRequest {
    return QueryParamsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(_: I): QueryParamsRequest {
    const message = createBaseQueryParamsRequest();
    return message;
  },
};

function createBaseQueryParamsResponse(): QueryParamsResponse {
  return { params: undefined };
}

export const QueryParamsResponse: MessageFns<QueryParamsResponse> = {
  encode(message: QueryParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryParamsResponse {
    return { params: isSet(object.params) ? Params.fromJSON(object.params) : undefined };
  },

  toJSON(message: QueryParamsResponse): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(base?: I): QueryParamsResponse {
    return QueryParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(object: I): QueryParamsResponse {
    const message = createBaseQueryParamsResponse();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseQueryReleaseRequest(): QueryReleaseRequest {
  return { id: 0 };
}

export const QueryReleaseRequest: MessageFns<QueryReleaseRequest> = {
  encode(message: QueryReleaseRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryReleaseRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryReleaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryReleaseRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: QueryReleaseRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryReleaseRequest>, I>>(base?: I): QueryReleaseRequest {
    return QueryReleaseRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryReleaseRequest>, I>>(object: I): QueryReleaseRequest {
    const message = createBaseQueryReleaseRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseQueryReleaseByIDRequest(): QueryReleaseByIDRequest {
  return { id: 0 };
}

export const QueryReleaseByIDRequest: MessageFns<QueryReleaseByIDRequest> = {
  encode(message: QueryReleaseByIDRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryReleaseByIDRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryReleaseByIDRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryReleaseByIDRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: QueryReleaseByIDRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryReleaseByIDRequest>, I>>(base?: I): QueryReleaseByIDRequest {
    return QueryReleaseByIDRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryReleaseByIDRequest>, I>>(object: I): QueryReleaseByIDRequest {
    const message = createBaseQueryReleaseByIDRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseQueryReleaseResponse(): QueryReleaseResponse {
  return { release: undefined };
}

export const QueryReleaseResponse: MessageFns<QueryReleaseResponse> = {
  encode(message: QueryReleaseResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.release !== undefined) {
      Release.encode(message.release, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryReleaseResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryReleaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.release = Release.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryReleaseResponse {
    return { release: isSet(object.release) ? Release.fromJSON(object.release) : undefined };
  },

  toJSON(message: QueryReleaseResponse): unknown {
    const obj: any = {};
    if (message.release !== undefined) {
      obj.release = Release.toJSON(message.release);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryReleaseResponse>, I>>(base?: I): QueryReleaseResponse {
    return QueryReleaseResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryReleaseResponse>, I>>(object: I): QueryReleaseResponse {
    const message = createBaseQueryReleaseResponse();
    message.release = (object.release !== undefined && object.release !== null)
      ? Release.fromPartial(object.release)
      : undefined;
    return message;
  },
};

function createBaseQueryReleasesRequest(): QueryReleasesRequest {
  return { page: 0, limit: 0 };
}

export const QueryReleasesRequest: MessageFns<QueryReleasesRequest> = {
  encode(message: QueryReleasesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.page !== 0) {
      writer.uint32(8).uint64(message.page);
    }
    if (message.limit !== 0) {
      writer.uint32(16).uint64(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryReleasesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryReleasesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.page = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryReleasesRequest {
    return {
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
    };
  },

  toJSON(message: QueryReleasesRequest): unknown {
    const obj: any = {};
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryReleasesRequest>, I>>(base?: I): QueryReleasesRequest {
    return QueryReleasesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryReleasesRequest>, I>>(object: I): QueryReleasesRequest {
    const message = createBaseQueryReleasesRequest();
    message.page = object.page ?? 0;
    message.limit = object.limit ?? 0;
    return message;
  },
};

function createBaseQueryReleasesResponse(): QueryReleasesResponse {
  return { releases: [], total: 0 };
}

export const QueryReleasesResponse: MessageFns<QueryReleasesResponse> = {
  encode(message: QueryReleasesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.releases) {
      Release.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(16).uint64(message.total);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryReleasesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryReleasesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.releases.push(Release.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryReleasesResponse {
    return {
      releases: globalThis.Array.isArray(object?.releases) ? object.releases.map((e: any) => Release.fromJSON(e)) : [],
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
    };
  },

  toJSON(message: QueryReleasesResponse): unknown {
    const obj: any = {};
    if (message.releases?.length) {
      obj.releases = message.releases.map((e) => Release.toJSON(e));
    }
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryReleasesResponse>, I>>(base?: I): QueryReleasesResponse {
    return QueryReleasesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryReleasesResponse>, I>>(object: I): QueryReleasesResponse {
    const message = createBaseQueryReleasesResponse();
    message.releases = object.releases?.map((e) => Release.fromPartial(e)) || [];
    message.total = object.total ?? 0;
    return message;
  },
};

function createBaseQueryLatestRequest(): QueryLatestRequest {
  return { channel: "", platform: "", kind: "" };
}

export const QueryLatestRequest: MessageFns<QueryLatestRequest> = {
  encode(message: QueryLatestRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.channel !== "") {
      writer.uint32(10).string(message.channel);
    }
    if (message.platform !== "") {
      writer.uint32(18).string(message.platform);
    }
    if (message.kind !== "") {
      writer.uint32(26).string(message.kind);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryLatestRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryLatestRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.channel = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.platform = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.kind = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryLatestRequest {
    return {
      channel: isSet(object.channel) ? globalThis.String(object.channel) : "",
      platform: isSet(object.platform) ? globalThis.String(object.platform) : "",
      kind: isSet(object.kind) ? globalThis.String(object.kind) : "",
    };
  },

  toJSON(message: QueryLatestRequest): unknown {
    const obj: any = {};
    if (message.channel !== "") {
      obj.channel = message.channel;
    }
    if (message.platform !== "") {
      obj.platform = message.platform;
    }
    if (message.kind !== "") {
      obj.kind = message.kind;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryLatestRequest>, I>>(base?: I): QueryLatestRequest {
    return QueryLatestRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryLatestRequest>, I>>(object: I): QueryLatestRequest {
    const message = createBaseQueryLatestRequest();
    message.channel = object.channel ?? "";
    message.platform = object.platform ?? "";
    message.kind = object.kind ?? "";
    return message;
  },
};

function createBaseQueryByVersionRequest(): QueryByVersionRequest {
  return { version: "" };
}

export const QueryByVersionRequest: MessageFns<QueryByVersionRequest> = {
  encode(message: QueryByVersionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.version !== "") {
      writer.uint32(10).string(message.version);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryByVersionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryByVersionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.version = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryByVersionRequest {
    return { version: isSet(object.version) ? globalThis.String(object.version) : "" };
  },

  toJSON(message: QueryByVersionRequest): unknown {
    const obj: any = {};
    if (message.version !== "") {
      obj.version = message.version;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryByVersionRequest>, I>>(base?: I): QueryByVersionRequest {
    return QueryByVersionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryByVersionRequest>, I>>(object: I): QueryByVersionRequest {
    const message = createBaseQueryByVersionRequest();
    message.version = object.version ?? "";
    return message;
  },
};

export interface Query {
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse>;
  Release(request: QueryReleaseRequest): Promise<QueryReleaseResponse>;
  ReleaseByID(request: QueryReleaseByIDRequest): Promise<QueryReleaseResponse>;
  Releases(request: QueryReleasesRequest): Promise<QueryReleasesResponse>;
  Latest(request: QueryLatestRequest): Promise<QueryReleaseResponse>;
  LatestCanon(request: QueryLatestRequest): Promise<QueryReleaseResponse>;
  ByVersion(request: QueryByVersionRequest): Promise<QueryReleaseResponse>;
}

export const QueryServiceName = "lumen.release.v1.Query";
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName;
    this.rpc = rpc;
    this.Params = this.Params.bind(this);
    this.Release = this.Release.bind(this);
    this.ReleaseByID = this.ReleaseByID.bind(this);
    this.Releases = this.Releases.bind(this);
    this.Latest = this.Latest.bind(this);
    this.LatestCanon = this.LatestCanon.bind(this);
    this.ByVersion = this.ByVersion.bind(this);
  }
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse> {
    const data = QueryParamsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Params", data);
    return promise.then((data) => QueryParamsResponse.decode(new BinaryReader(data)));
  }

  Release(request: QueryReleaseRequest): Promise<QueryReleaseResponse> {
    const data = QueryReleaseRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Release", data);
    return promise.then((data) => QueryReleaseResponse.decode(new BinaryReader(data)));
  }

  ReleaseByID(request: QueryReleaseByIDRequest): Promise<QueryReleaseResponse> {
    const data = QueryReleaseByIDRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ReleaseByID", data);
    return promise.then((data) => QueryReleaseResponse.decode(new BinaryReader(data)));
  }

  Releases(request: QueryReleasesRequest): Promise<QueryReleasesResponse> {
    const data = QueryReleasesRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Releases", data);
    return promise.then((data) => QueryReleasesResponse.decode(new BinaryReader(data)));
  }

  Latest(request: QueryLatestRequest): Promise<QueryReleaseResponse> {
    const data = QueryLatestRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Latest", data);
    return promise.then((data) => QueryReleaseResponse.decode(new BinaryReader(data)));
  }

  LatestCanon(request: QueryLatestRequest): Promise<QueryReleaseResponse> {
    const data = QueryLatestRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "LatestCanon", data);
    return promise.then((data) => QueryReleaseResponse.decode(new BinaryReader(data)));
  }

  ByVersion(request: QueryByVersionRequest): Promise<QueryReleaseResponse> {
    const data = QueryByVersionRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ByVersion", data);
    return promise.then((data) => QueryReleaseResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
