// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: lumen/release/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";
import { Release } from "./types";

export const protobufPackage = "lumen.release.v1";

export interface MsgPublishRelease {
  creator: string;
  release: Release | undefined;
}

export interface MsgPublishReleaseResponse {
  id: number;
}

export interface MsgYankRelease {
  creator: string;
  id: number;
}

export interface MsgYankReleaseResponse {
}

export interface MsgMirrorRelease {
  creator: string;
  id: number;
  artifactIndex: number;
  newUrls: string[];
}

export interface MsgMirrorReleaseResponse {
  added: number;
}

export interface MsgSetEmergency {
  creator: string;
  id: number;
  emergencyOk: boolean;
  /** seconds from now (<= params.max_pending_ttl) */
  emergencyTtl: number;
}

export interface MsgSetEmergencyResponse {
}

export interface MsgValidateRelease {
  authority: string;
  id: number;
}

export interface MsgValidateReleaseResponse {
}

export interface MsgRejectRelease {
  authority: string;
  id: number;
}

export interface MsgRejectReleaseResponse {
}

export interface MsgUpdateParams {
  authority: string;
  params: Params | undefined;
}

export interface MsgUpdateParamsResponse {
}

function createBaseMsgPublishRelease(): MsgPublishRelease {
  return { creator: "", release: undefined };
}

export const MsgPublishRelease: MessageFns<MsgPublishRelease> = {
  encode(message: MsgPublishRelease, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.release !== undefined) {
      Release.encode(message.release, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgPublishRelease {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgPublishRelease();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.release = Release.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgPublishRelease {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      release: isSet(object.release) ? Release.fromJSON(object.release) : undefined,
    };
  },

  toJSON(message: MsgPublishRelease): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.release !== undefined) {
      obj.release = Release.toJSON(message.release);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgPublishRelease>, I>>(base?: I): MsgPublishRelease {
    return MsgPublishRelease.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgPublishRelease>, I>>(object: I): MsgPublishRelease {
    const message = createBaseMsgPublishRelease();
    message.creator = object.creator ?? "";
    message.release = (object.release !== undefined && object.release !== null)
      ? Release.fromPartial(object.release)
      : undefined;
    return message;
  },
};

function createBaseMsgPublishReleaseResponse(): MsgPublishReleaseResponse {
  return { id: 0 };
}

export const MsgPublishReleaseResponse: MessageFns<MsgPublishReleaseResponse> = {
  encode(message: MsgPublishReleaseResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgPublishReleaseResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgPublishReleaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgPublishReleaseResponse {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: MsgPublishReleaseResponse): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgPublishReleaseResponse>, I>>(base?: I): MsgPublishReleaseResponse {
    return MsgPublishReleaseResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgPublishReleaseResponse>, I>>(object: I): MsgPublishReleaseResponse {
    const message = createBaseMsgPublishReleaseResponse();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseMsgYankRelease(): MsgYankRelease {
  return { creator: "", id: 0 };
}

export const MsgYankRelease: MessageFns<MsgYankRelease> = {
  encode(message: MsgYankRelease, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.id !== 0) {
      writer.uint32(16).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgYankRelease {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgYankRelease();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgYankRelease {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
    };
  },

  toJSON(message: MsgYankRelease): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgYankRelease>, I>>(base?: I): MsgYankRelease {
    return MsgYankRelease.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgYankRelease>, I>>(object: I): MsgYankRelease {
    const message = createBaseMsgYankRelease();
    message.creator = object.creator ?? "";
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseMsgYankReleaseResponse(): MsgYankReleaseResponse {
  return {};
}

export const MsgYankReleaseResponse: MessageFns<MsgYankReleaseResponse> = {
  encode(_: MsgYankReleaseResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgYankReleaseResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgYankReleaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgYankReleaseResponse {
    return {};
  },

  toJSON(_: MsgYankReleaseResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgYankReleaseResponse>, I>>(base?: I): MsgYankReleaseResponse {
    return MsgYankReleaseResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgYankReleaseResponse>, I>>(_: I): MsgYankReleaseResponse {
    const message = createBaseMsgYankReleaseResponse();
    return message;
  },
};

function createBaseMsgMirrorRelease(): MsgMirrorRelease {
  return { creator: "", id: 0, artifactIndex: 0, newUrls: [] };
}

export const MsgMirrorRelease: MessageFns<MsgMirrorRelease> = {
  encode(message: MsgMirrorRelease, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.id !== 0) {
      writer.uint32(16).uint64(message.id);
    }
    if (message.artifactIndex !== 0) {
      writer.uint32(24).uint32(message.artifactIndex);
    }
    for (const v of message.newUrls) {
      writer.uint32(34).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgMirrorRelease {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgMirrorRelease();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.artifactIndex = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.newUrls.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgMirrorRelease {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      artifactIndex: isSet(object.artifactIndex) ? globalThis.Number(object.artifactIndex) : 0,
      newUrls: globalThis.Array.isArray(object?.newUrls) ? object.newUrls.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: MsgMirrorRelease): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.artifactIndex !== 0) {
      obj.artifactIndex = Math.round(message.artifactIndex);
    }
    if (message.newUrls?.length) {
      obj.newUrls = message.newUrls;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgMirrorRelease>, I>>(base?: I): MsgMirrorRelease {
    return MsgMirrorRelease.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgMirrorRelease>, I>>(object: I): MsgMirrorRelease {
    const message = createBaseMsgMirrorRelease();
    message.creator = object.creator ?? "";
    message.id = object.id ?? 0;
    message.artifactIndex = object.artifactIndex ?? 0;
    message.newUrls = object.newUrls?.map((e) => e) || [];
    return message;
  },
};

function createBaseMsgMirrorReleaseResponse(): MsgMirrorReleaseResponse {
  return { added: 0 };
}

export const MsgMirrorReleaseResponse: MessageFns<MsgMirrorReleaseResponse> = {
  encode(message: MsgMirrorReleaseResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.added !== 0) {
      writer.uint32(8).uint32(message.added);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgMirrorReleaseResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgMirrorReleaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.added = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgMirrorReleaseResponse {
    return { added: isSet(object.added) ? globalThis.Number(object.added) : 0 };
  },

  toJSON(message: MsgMirrorReleaseResponse): unknown {
    const obj: any = {};
    if (message.added !== 0) {
      obj.added = Math.round(message.added);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgMirrorReleaseResponse>, I>>(base?: I): MsgMirrorReleaseResponse {
    return MsgMirrorReleaseResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgMirrorReleaseResponse>, I>>(object: I): MsgMirrorReleaseResponse {
    const message = createBaseMsgMirrorReleaseResponse();
    message.added = object.added ?? 0;
    return message;
  },
};

function createBaseMsgSetEmergency(): MsgSetEmergency {
  return { creator: "", id: 0, emergencyOk: false, emergencyTtl: 0 };
}

export const MsgSetEmergency: MessageFns<MsgSetEmergency> = {
  encode(message: MsgSetEmergency, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.id !== 0) {
      writer.uint32(16).uint64(message.id);
    }
    if (message.emergencyOk !== false) {
      writer.uint32(24).bool(message.emergencyOk);
    }
    if (message.emergencyTtl !== 0) {
      writer.uint32(32).int64(message.emergencyTtl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSetEmergency {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSetEmergency();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.emergencyOk = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.emergencyTtl = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSetEmergency {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      emergencyOk: isSet(object.emergencyOk) ? globalThis.Boolean(object.emergencyOk) : false,
      emergencyTtl: isSet(object.emergencyTtl) ? globalThis.Number(object.emergencyTtl) : 0,
    };
  },

  toJSON(message: MsgSetEmergency): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.emergencyOk !== false) {
      obj.emergencyOk = message.emergencyOk;
    }
    if (message.emergencyTtl !== 0) {
      obj.emergencyTtl = Math.round(message.emergencyTtl);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSetEmergency>, I>>(base?: I): MsgSetEmergency {
    return MsgSetEmergency.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSetEmergency>, I>>(object: I): MsgSetEmergency {
    const message = createBaseMsgSetEmergency();
    message.creator = object.creator ?? "";
    message.id = object.id ?? 0;
    message.emergencyOk = object.emergencyOk ?? false;
    message.emergencyTtl = object.emergencyTtl ?? 0;
    return message;
  },
};

function createBaseMsgSetEmergencyResponse(): MsgSetEmergencyResponse {
  return {};
}

export const MsgSetEmergencyResponse: MessageFns<MsgSetEmergencyResponse> = {
  encode(_: MsgSetEmergencyResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSetEmergencyResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSetEmergencyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgSetEmergencyResponse {
    return {};
  },

  toJSON(_: MsgSetEmergencyResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSetEmergencyResponse>, I>>(base?: I): MsgSetEmergencyResponse {
    return MsgSetEmergencyResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSetEmergencyResponse>, I>>(_: I): MsgSetEmergencyResponse {
    const message = createBaseMsgSetEmergencyResponse();
    return message;
  },
};

function createBaseMsgValidateRelease(): MsgValidateRelease {
  return { authority: "", id: 0 };
}

export const MsgValidateRelease: MessageFns<MsgValidateRelease> = {
  encode(message: MsgValidateRelease, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.id !== 0) {
      writer.uint32(16).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgValidateRelease {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgValidateRelease();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgValidateRelease {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
    };
  },

  toJSON(message: MsgValidateRelease): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgValidateRelease>, I>>(base?: I): MsgValidateRelease {
    return MsgValidateRelease.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgValidateRelease>, I>>(object: I): MsgValidateRelease {
    const message = createBaseMsgValidateRelease();
    message.authority = object.authority ?? "";
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseMsgValidateReleaseResponse(): MsgValidateReleaseResponse {
  return {};
}

export const MsgValidateReleaseResponse: MessageFns<MsgValidateReleaseResponse> = {
  encode(_: MsgValidateReleaseResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgValidateReleaseResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgValidateReleaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgValidateReleaseResponse {
    return {};
  },

  toJSON(_: MsgValidateReleaseResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgValidateReleaseResponse>, I>>(base?: I): MsgValidateReleaseResponse {
    return MsgValidateReleaseResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgValidateReleaseResponse>, I>>(_: I): MsgValidateReleaseResponse {
    const message = createBaseMsgValidateReleaseResponse();
    return message;
  },
};

function createBaseMsgRejectRelease(): MsgRejectRelease {
  return { authority: "", id: 0 };
}

export const MsgRejectRelease: MessageFns<MsgRejectRelease> = {
  encode(message: MsgRejectRelease, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.id !== 0) {
      writer.uint32(16).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRejectRelease {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRejectRelease();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRejectRelease {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
    };
  },

  toJSON(message: MsgRejectRelease): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRejectRelease>, I>>(base?: I): MsgRejectRelease {
    return MsgRejectRelease.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRejectRelease>, I>>(object: I): MsgRejectRelease {
    const message = createBaseMsgRejectRelease();
    message.authority = object.authority ?? "";
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseMsgRejectReleaseResponse(): MsgRejectReleaseResponse {
  return {};
}

export const MsgRejectReleaseResponse: MessageFns<MsgRejectReleaseResponse> = {
  encode(_: MsgRejectReleaseResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRejectReleaseResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRejectReleaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgRejectReleaseResponse {
    return {};
  },

  toJSON(_: MsgRejectReleaseResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRejectReleaseResponse>, I>>(base?: I): MsgRejectReleaseResponse {
    return MsgRejectReleaseResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRejectReleaseResponse>, I>>(_: I): MsgRejectReleaseResponse {
    const message = createBaseMsgRejectReleaseResponse();
    return message;
  },
};

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

export interface Msg {
  PublishRelease(request: MsgPublishRelease): Promise<MsgPublishReleaseResponse>;
  YankRelease(request: MsgYankRelease): Promise<MsgYankReleaseResponse>;
  MirrorRelease(request: MsgMirrorRelease): Promise<MsgMirrorReleaseResponse>;
  SetEmergency(request: MsgSetEmergency): Promise<MsgSetEmergencyResponse>;
  ValidateRelease(request: MsgValidateRelease): Promise<MsgValidateReleaseResponse>;
  RejectRelease(request: MsgRejectRelease): Promise<MsgRejectReleaseResponse>;
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse>;
}

export const MsgServiceName = "lumen.release.v1.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.PublishRelease = this.PublishRelease.bind(this);
    this.YankRelease = this.YankRelease.bind(this);
    this.MirrorRelease = this.MirrorRelease.bind(this);
    this.SetEmergency = this.SetEmergency.bind(this);
    this.ValidateRelease = this.ValidateRelease.bind(this);
    this.RejectRelease = this.RejectRelease.bind(this);
    this.UpdateParams = this.UpdateParams.bind(this);
  }
  PublishRelease(request: MsgPublishRelease): Promise<MsgPublishReleaseResponse> {
    const data = MsgPublishRelease.encode(request).finish();
    const promise = this.rpc.request(this.service, "PublishRelease", data);
    return promise.then((data) => MsgPublishReleaseResponse.decode(new BinaryReader(data)));
  }

  YankRelease(request: MsgYankRelease): Promise<MsgYankReleaseResponse> {
    const data = MsgYankRelease.encode(request).finish();
    const promise = this.rpc.request(this.service, "YankRelease", data);
    return promise.then((data) => MsgYankReleaseResponse.decode(new BinaryReader(data)));
  }

  MirrorRelease(request: MsgMirrorRelease): Promise<MsgMirrorReleaseResponse> {
    const data = MsgMirrorRelease.encode(request).finish();
    const promise = this.rpc.request(this.service, "MirrorRelease", data);
    return promise.then((data) => MsgMirrorReleaseResponse.decode(new BinaryReader(data)));
  }

  SetEmergency(request: MsgSetEmergency): Promise<MsgSetEmergencyResponse> {
    const data = MsgSetEmergency.encode(request).finish();
    const promise = this.rpc.request(this.service, "SetEmergency", data);
    return promise.then((data) => MsgSetEmergencyResponse.decode(new BinaryReader(data)));
  }

  ValidateRelease(request: MsgValidateRelease): Promise<MsgValidateReleaseResponse> {
    const data = MsgValidateRelease.encode(request).finish();
    const promise = this.rpc.request(this.service, "ValidateRelease", data);
    return promise.then((data) => MsgValidateReleaseResponse.decode(new BinaryReader(data)));
  }

  RejectRelease(request: MsgRejectRelease): Promise<MsgRejectReleaseResponse> {
    const data = MsgRejectRelease.encode(request).finish();
    const promise = this.rpc.request(this.service, "RejectRelease", data);
    return promise.then((data) => MsgRejectReleaseResponse.decode(new BinaryReader(data)));
  }

  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse> {
    const data = MsgUpdateParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateParams", data);
    return promise.then((data) => MsgUpdateParamsResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
