// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: lumen/release/v1/types.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "lumen.release.v1";

export interface Signature {
  /** label/hex ID (info only v1) */
  keyId: string;
  /** e.g. "ed25519" (v1) */
  algo: string;
  /** raw bytes; JSON base64 */
  sig: Uint8Array;
}

export interface Artifact {
  /** e.g., "linux-amd64" */
  platform: string;
  /** e.g., "daemon", "cli", "bundle" */
  kind: string;
  /** optional IPFS CID */
  cid: string;
  /** required */
  sha256Hex: string;
  /** bytes */
  size: number;
  /** http(s)/ipfs gateways mirrors */
  urls: string[];
  signatures: Signature[];
}

export interface Release {
  id: number;
  /** semver */
  version: string;
  /** stable/beta/nightly */
  channel: string;
  /** 1..N */
  artifacts: Artifact[];
  /** bech32 of signer */
  publisher: string;
  /** short (bounded) */
  notes: string;
  /** unix time (block) */
  createdAt: number;
  yanked: boolean;
  supersedes: number[];
  status: Release_ReleaseStatus;
  emergencyOk: boolean;
  /** unix time until which emergency_ok applies */
  emergencyUntil: number;
}

export enum Release_ReleaseStatus {
  PENDING = 0,
  VALIDATED = 1,
  REJECTED = 2,
  EXPIRED = 3,
  UNRECOGNIZED = -1,
}

export function release_ReleaseStatusFromJSON(object: any): Release_ReleaseStatus {
  switch (object) {
    case 0:
    case "PENDING":
      return Release_ReleaseStatus.PENDING;
    case 1:
    case "VALIDATED":
      return Release_ReleaseStatus.VALIDATED;
    case 2:
    case "REJECTED":
      return Release_ReleaseStatus.REJECTED;
    case 3:
    case "EXPIRED":
      return Release_ReleaseStatus.EXPIRED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Release_ReleaseStatus.UNRECOGNIZED;
  }
}

export function release_ReleaseStatusToJSON(object: Release_ReleaseStatus): string {
  switch (object) {
    case Release_ReleaseStatus.PENDING:
      return "PENDING";
    case Release_ReleaseStatus.VALIDATED:
      return "VALIDATED";
    case Release_ReleaseStatus.REJECTED:
      return "REJECTED";
    case Release_ReleaseStatus.EXPIRED:
      return "EXPIRED";
    case Release_ReleaseStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

function createBaseSignature(): Signature {
  return { keyId: "", algo: "", sig: new Uint8Array(0) };
}

export const Signature: MessageFns<Signature> = {
  encode(message: Signature, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.keyId !== "") {
      writer.uint32(10).string(message.keyId);
    }
    if (message.algo !== "") {
      writer.uint32(18).string(message.algo);
    }
    if (message.sig.length !== 0) {
      writer.uint32(26).bytes(message.sig);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Signature {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignature();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.keyId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.algo = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sig = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Signature {
    return {
      keyId: isSet(object.keyId)
        ? globalThis.String(object.keyId)
        : isSet(object.key_id)
        ? globalThis.String(object.key_id)
        : "",
      algo: isSet(object.algo) ? globalThis.String(object.algo) : "",
      sig: isSet(object.sig) ? bytesFromBase64(object.sig) : new Uint8Array(0),
    };
  },

  toJSON(message: Signature): unknown {
    const obj: any = {};
    if (message.keyId !== "") {
      obj.keyId = message.keyId;
    }
    if (message.algo !== "") {
      obj.algo = message.algo;
    }
    if (message.sig.length !== 0) {
      obj.sig = base64FromBytes(message.sig);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Signature>, I>>(base?: I): Signature {
    return Signature.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Signature>, I>>(object: I): Signature {
    const message = createBaseSignature();
    message.keyId = object.keyId ?? "";
    message.algo = object.algo ?? "";
    message.sig = object.sig ?? new Uint8Array(0);
    return message;
  },
};

function createBaseArtifact(): Artifact {
  return { platform: "", kind: "", cid: "", sha256Hex: "", size: 0, urls: [], signatures: [] };
}

export const Artifact: MessageFns<Artifact> = {
  encode(message: Artifact, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.platform !== "") {
      writer.uint32(10).string(message.platform);
    }
    if (message.kind !== "") {
      writer.uint32(18).string(message.kind);
    }
    if (message.cid !== "") {
      writer.uint32(26).string(message.cid);
    }
    if (message.sha256Hex !== "") {
      writer.uint32(34).string(message.sha256Hex);
    }
    if (message.size !== 0) {
      writer.uint32(40).uint64(message.size);
    }
    for (const v of message.urls) {
      writer.uint32(50).string(v!);
    }
    for (const v of message.signatures) {
      Signature.encode(v!, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Artifact {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseArtifact();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.platform = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.kind = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.cid = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.sha256Hex = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.size = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.urls.push(reader.string());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.signatures.push(Signature.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Artifact {
    return {
      platform: isSet(object.platform) ? globalThis.String(object.platform) : "",
      kind: isSet(object.kind) ? globalThis.String(object.kind) : "",
      cid: isSet(object.cid) ? globalThis.String(object.cid) : "",
      sha256Hex: isSet(object.sha256Hex)
        ? globalThis.String(object.sha256Hex)
        : isSet(object.sha256_hex)
        ? globalThis.String(object.sha256_hex)
        : "",
      size: isSet(object.size) ? globalThis.Number(object.size) : 0,
      urls: globalThis.Array.isArray(object?.urls) ? object.urls.map((e: any) => globalThis.String(e)) : [],
      signatures: globalThis.Array.isArray(object?.signatures)
        ? object.signatures.map((e: any) => Signature.fromJSON(e))
        : [],
    };
  },

  toJSON(message: Artifact): unknown {
    const obj: any = {};
    if (message.platform !== "") {
      obj.platform = message.platform;
    }
    if (message.kind !== "") {
      obj.kind = message.kind;
    }
    if (message.cid !== "") {
      obj.cid = message.cid;
    }
    if (message.sha256Hex !== "") {
      obj.sha256Hex = message.sha256Hex;
    }
    if (message.size !== 0) {
      obj.size = Math.round(message.size);
    }
    if (message.urls?.length) {
      obj.urls = message.urls;
    }
    if (message.signatures?.length) {
      obj.signatures = message.signatures.map((e) => Signature.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Artifact>, I>>(base?: I): Artifact {
    return Artifact.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Artifact>, I>>(object: I): Artifact {
    const message = createBaseArtifact();
    message.platform = object.platform ?? "";
    message.kind = object.kind ?? "";
    message.cid = object.cid ?? "";
    message.sha256Hex = object.sha256Hex ?? "";
    message.size = object.size ?? 0;
    message.urls = object.urls?.map((e) => e) || [];
    message.signatures = object.signatures?.map((e) => Signature.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRelease(): Release {
  return {
    id: 0,
    version: "",
    channel: "",
    artifacts: [],
    publisher: "",
    notes: "",
    createdAt: 0,
    yanked: false,
    supersedes: [],
    status: 0,
    emergencyOk: false,
    emergencyUntil: 0,
  };
}

export const Release: MessageFns<Release> = {
  encode(message: Release, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.version !== "") {
      writer.uint32(18).string(message.version);
    }
    if (message.channel !== "") {
      writer.uint32(26).string(message.channel);
    }
    for (const v of message.artifacts) {
      Artifact.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.publisher !== "") {
      writer.uint32(42).string(message.publisher);
    }
    if (message.notes !== "") {
      writer.uint32(50).string(message.notes);
    }
    if (message.createdAt !== 0) {
      writer.uint32(56).int64(message.createdAt);
    }
    if (message.yanked !== false) {
      writer.uint32(64).bool(message.yanked);
    }
    writer.uint32(74).fork();
    for (const v of message.supersedes) {
      writer.uint64(v);
    }
    writer.join();
    if (message.status !== 0) {
      writer.uint32(80).int32(message.status);
    }
    if (message.emergencyOk !== false) {
      writer.uint32(88).bool(message.emergencyOk);
    }
    if (message.emergencyUntil !== 0) {
      writer.uint32(96).int64(message.emergencyUntil);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Release {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRelease();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.version = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.channel = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.artifacts.push(Artifact.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.publisher = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.notes = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.createdAt = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.yanked = reader.bool();
          continue;
        }
        case 9: {
          if (tag === 72) {
            message.supersedes.push(longToNumber(reader.uint64()));

            continue;
          }

          if (tag === 74) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.supersedes.push(longToNumber(reader.uint64()));
            }

            continue;
          }

          break;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.emergencyOk = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.emergencyUntil = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Release {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      version: isSet(object.version) ? globalThis.String(object.version) : "",
      channel: isSet(object.channel) ? globalThis.String(object.channel) : "",
      artifacts: globalThis.Array.isArray(object?.artifacts)
        ? object.artifacts.map((e: any) => Artifact.fromJSON(e))
        : [],
      publisher: isSet(object.publisher) ? globalThis.String(object.publisher) : "",
      notes: isSet(object.notes) ? globalThis.String(object.notes) : "",
      createdAt: isSet(object.createdAt)
        ? globalThis.Number(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.Number(object.created_at)
        : 0,
      yanked: isSet(object.yanked) ? globalThis.Boolean(object.yanked) : false,
      supersedes: globalThis.Array.isArray(object?.supersedes)
        ? object.supersedes.map((e: any) => globalThis.Number(e))
        : [],
      status: isSet(object.status) ? release_ReleaseStatusFromJSON(object.status) : 0,
      emergencyOk: isSet(object.emergencyOk)
        ? globalThis.Boolean(object.emergencyOk)
        : isSet(object.emergency_ok)
        ? globalThis.Boolean(object.emergency_ok)
        : false,
      emergencyUntil: isSet(object.emergencyUntil)
        ? globalThis.Number(object.emergencyUntil)
        : isSet(object.emergency_until)
        ? globalThis.Number(object.emergency_until)
        : 0,
    };
  },

  toJSON(message: Release): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.version !== "") {
      obj.version = message.version;
    }
    if (message.channel !== "") {
      obj.channel = message.channel;
    }
    if (message.artifacts?.length) {
      obj.artifacts = message.artifacts.map((e) => Artifact.toJSON(e));
    }
    if (message.publisher !== "") {
      obj.publisher = message.publisher;
    }
    if (message.notes !== "") {
      obj.notes = message.notes;
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    if (message.yanked !== false) {
      obj.yanked = message.yanked;
    }
    if (message.supersedes?.length) {
      obj.supersedes = message.supersedes.map((e) => Math.round(e));
    }
    if (message.status !== 0) {
      obj.status = release_ReleaseStatusToJSON(message.status);
    }
    if (message.emergencyOk !== false) {
      obj.emergencyOk = message.emergencyOk;
    }
    if (message.emergencyUntil !== 0) {
      obj.emergencyUntil = Math.round(message.emergencyUntil);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Release>, I>>(base?: I): Release {
    return Release.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Release>, I>>(object: I): Release {
    const message = createBaseRelease();
    message.id = object.id ?? 0;
    message.version = object.version ?? "";
    message.channel = object.channel ?? "";
    message.artifacts = object.artifacts?.map((e) => Artifact.fromPartial(e)) || [];
    message.publisher = object.publisher ?? "";
    message.notes = object.notes ?? "";
    message.createdAt = object.createdAt ?? 0;
    message.yanked = object.yanked ?? false;
    message.supersedes = object.supersedes?.map((e) => e) || [];
    message.status = object.status ?? 0;
    message.emergencyOk = object.emergencyOk ?? false;
    message.emergencyUntil = object.emergencyUntil ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
