// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: lumen/gateway/v1/params.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "lumen.gateway.v1";

export interface Params {
  platformCommissionBps: number;
  monthSeconds: number;
  finalizeDelayMonths: number;
  finalizerRewardBps: number;
  minPriceUlmnPerMonth: number;
  maxActiveContractsPerGateway: number;
  actionFeeUlmn: number;
  registerGatewayFeeUlmn: number;
}

function createBaseParams(): Params {
  return {
    platformCommissionBps: 0,
    monthSeconds: 0,
    finalizeDelayMonths: 0,
    finalizerRewardBps: 0,
    minPriceUlmnPerMonth: 0,
    maxActiveContractsPerGateway: 0,
    actionFeeUlmn: 0,
    registerGatewayFeeUlmn: 0,
  };
}

export const Params: MessageFns<Params> = {
  encode(message: Params, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.platformCommissionBps !== 0) {
      writer.uint32(8).uint32(message.platformCommissionBps);
    }
    if (message.monthSeconds !== 0) {
      writer.uint32(16).uint64(message.monthSeconds);
    }
    if (message.finalizeDelayMonths !== 0) {
      writer.uint32(24).uint32(message.finalizeDelayMonths);
    }
    if (message.finalizerRewardBps !== 0) {
      writer.uint32(32).uint32(message.finalizerRewardBps);
    }
    if (message.minPriceUlmnPerMonth !== 0) {
      writer.uint32(40).uint64(message.minPriceUlmnPerMonth);
    }
    if (message.maxActiveContractsPerGateway !== 0) {
      writer.uint32(48).uint32(message.maxActiveContractsPerGateway);
    }
    if (message.actionFeeUlmn !== 0) {
      writer.uint32(56).uint64(message.actionFeeUlmn);
    }
    if (message.registerGatewayFeeUlmn !== 0) {
      writer.uint32(64).uint64(message.registerGatewayFeeUlmn);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Params {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.platformCommissionBps = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.monthSeconds = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.finalizeDelayMonths = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.finalizerRewardBps = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.minPriceUlmnPerMonth = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.maxActiveContractsPerGateway = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.actionFeeUlmn = longToNumber(reader.uint64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.registerGatewayFeeUlmn = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      platformCommissionBps: isSet(object.platformCommissionBps) ? globalThis.Number(object.platformCommissionBps) : 0,
      monthSeconds: isSet(object.monthSeconds) ? globalThis.Number(object.monthSeconds) : 0,
      finalizeDelayMonths: isSet(object.finalizeDelayMonths) ? globalThis.Number(object.finalizeDelayMonths) : 0,
      finalizerRewardBps: isSet(object.finalizerRewardBps) ? globalThis.Number(object.finalizerRewardBps) : 0,
      minPriceUlmnPerMonth: isSet(object.minPriceUlmnPerMonth) ? globalThis.Number(object.minPriceUlmnPerMonth) : 0,
      maxActiveContractsPerGateway: isSet(object.maxActiveContractsPerGateway)
        ? globalThis.Number(object.maxActiveContractsPerGateway)
        : 0,
      actionFeeUlmn: isSet(object.actionFeeUlmn) ? globalThis.Number(object.actionFeeUlmn) : 0,
      registerGatewayFeeUlmn: isSet(object.registerGatewayFeeUlmn)
        ? globalThis.Number(object.registerGatewayFeeUlmn)
        : 0,
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (message.platformCommissionBps !== 0) {
      obj.platformCommissionBps = Math.round(message.platformCommissionBps);
    }
    if (message.monthSeconds !== 0) {
      obj.monthSeconds = Math.round(message.monthSeconds);
    }
    if (message.finalizeDelayMonths !== 0) {
      obj.finalizeDelayMonths = Math.round(message.finalizeDelayMonths);
    }
    if (message.finalizerRewardBps !== 0) {
      obj.finalizerRewardBps = Math.round(message.finalizerRewardBps);
    }
    if (message.minPriceUlmnPerMonth !== 0) {
      obj.minPriceUlmnPerMonth = Math.round(message.minPriceUlmnPerMonth);
    }
    if (message.maxActiveContractsPerGateway !== 0) {
      obj.maxActiveContractsPerGateway = Math.round(message.maxActiveContractsPerGateway);
    }
    if (message.actionFeeUlmn !== 0) {
      obj.actionFeeUlmn = Math.round(message.actionFeeUlmn);
    }
    if (message.registerGatewayFeeUlmn !== 0) {
      obj.registerGatewayFeeUlmn = Math.round(message.registerGatewayFeeUlmn);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Params>, I>>(base?: I): Params {
    return Params.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Params>, I>>(object: I): Params {
    const message = createBaseParams();
    message.platformCommissionBps = object.platformCommissionBps ?? 0;
    message.monthSeconds = object.monthSeconds ?? 0;
    message.finalizeDelayMonths = object.finalizeDelayMonths ?? 0;
    message.finalizerRewardBps = object.finalizerRewardBps ?? 0;
    message.minPriceUlmnPerMonth = object.minPriceUlmnPerMonth ?? 0;
    message.maxActiveContractsPerGateway = object.maxActiveContractsPerGateway ?? 0;
    message.actionFeeUlmn = object.actionFeeUlmn ?? 0;
    message.registerGatewayFeeUlmn = object.registerGatewayFeeUlmn ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
