// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: lumen/gateway/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { BoolValue, StringValue } from "../../../google/protobuf/wrappers";
import { Params } from "./params";

export const protobufPackage = "lumen.gateway.v1";

export interface MsgRegisterGateway {
  operator: string;
  payout: string;
  metadata: string;
}

export interface MsgRegisterGatewayResponse {
  id: number;
}

export interface MsgUpdateGateway {
  operator: string;
  gatewayId: number;
  payout: string | undefined;
  metadata: string | undefined;
  active: boolean | undefined;
}

export interface MsgUpdateGatewayResponse {
}

export interface MsgUpdateParams {
  authority: string;
  params: Params | undefined;
}

export interface MsgUpdateParamsResponse {
}

export interface MsgCreateContract {
  client: string;
  gatewayId: number;
  priceUlmn: number;
  storageGbPerMonth: number;
  networkGbPerMonth: number;
  monthsTotal: number;
  metadata: string;
}

export interface MsgCreateContractResponse {
  contractId: number;
}

export interface MsgClaimPayment {
  operator: string;
  contractId: number;
}

export interface MsgClaimPaymentResponse {
  paidUlmn: string;
}

export interface MsgCancelContract {
  client: string;
  contractId: number;
}

export interface MsgCancelContractResponse {
  refundedUlmn: string;
}

export interface MsgFinalizeContract {
  finalizer: string;
  contractId: number;
}

export interface MsgFinalizeContractResponse {
  rewardUlmn: string;
}

function createBaseMsgRegisterGateway(): MsgRegisterGateway {
  return { operator: "", payout: "", metadata: "" };
}

export const MsgRegisterGateway: MessageFns<MsgRegisterGateway> = {
  encode(message: MsgRegisterGateway, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.operator !== "") {
      writer.uint32(10).string(message.operator);
    }
    if (message.payout !== "") {
      writer.uint32(18).string(message.payout);
    }
    if (message.metadata !== "") {
      writer.uint32(26).string(message.metadata);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRegisterGateway {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRegisterGateway();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.operator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.payout = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.metadata = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRegisterGateway {
    return {
      operator: isSet(object.operator) ? globalThis.String(object.operator) : "",
      payout: isSet(object.payout) ? globalThis.String(object.payout) : "",
      metadata: isSet(object.metadata) ? globalThis.String(object.metadata) : "",
    };
  },

  toJSON(message: MsgRegisterGateway): unknown {
    const obj: any = {};
    if (message.operator !== "") {
      obj.operator = message.operator;
    }
    if (message.payout !== "") {
      obj.payout = message.payout;
    }
    if (message.metadata !== "") {
      obj.metadata = message.metadata;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegisterGateway>, I>>(base?: I): MsgRegisterGateway {
    return MsgRegisterGateway.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegisterGateway>, I>>(object: I): MsgRegisterGateway {
    const message = createBaseMsgRegisterGateway();
    message.operator = object.operator ?? "";
    message.payout = object.payout ?? "";
    message.metadata = object.metadata ?? "";
    return message;
  },
};

function createBaseMsgRegisterGatewayResponse(): MsgRegisterGatewayResponse {
  return { id: 0 };
}

export const MsgRegisterGatewayResponse: MessageFns<MsgRegisterGatewayResponse> = {
  encode(message: MsgRegisterGatewayResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRegisterGatewayResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRegisterGatewayResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRegisterGatewayResponse {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: MsgRegisterGatewayResponse): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegisterGatewayResponse>, I>>(base?: I): MsgRegisterGatewayResponse {
    return MsgRegisterGatewayResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegisterGatewayResponse>, I>>(object: I): MsgRegisterGatewayResponse {
    const message = createBaseMsgRegisterGatewayResponse();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseMsgUpdateGateway(): MsgUpdateGateway {
  return { operator: "", gatewayId: 0, payout: undefined, metadata: undefined, active: undefined };
}

export const MsgUpdateGateway: MessageFns<MsgUpdateGateway> = {
  encode(message: MsgUpdateGateway, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.operator !== "") {
      writer.uint32(10).string(message.operator);
    }
    if (message.gatewayId !== 0) {
      writer.uint32(16).uint64(message.gatewayId);
    }
    if (message.payout !== undefined) {
      StringValue.encode({ value: message.payout! }, writer.uint32(26).fork()).join();
    }
    if (message.metadata !== undefined) {
      StringValue.encode({ value: message.metadata! }, writer.uint32(34).fork()).join();
    }
    if (message.active !== undefined) {
      BoolValue.encode({ value: message.active! }, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateGateway {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateGateway();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.operator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.gatewayId = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.payout = StringValue.decode(reader, reader.uint32()).value;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.metadata = StringValue.decode(reader, reader.uint32()).value;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.active = BoolValue.decode(reader, reader.uint32()).value;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateGateway {
    return {
      operator: isSet(object.operator) ? globalThis.String(object.operator) : "",
      gatewayId: isSet(object.gatewayId) ? globalThis.Number(object.gatewayId) : 0,
      payout: isSet(object.payout) ? String(object.payout) : undefined,
      metadata: isSet(object.metadata) ? String(object.metadata) : undefined,
      active: isSet(object.active) ? Boolean(object.active) : undefined,
    };
  },

  toJSON(message: MsgUpdateGateway): unknown {
    const obj: any = {};
    if (message.operator !== "") {
      obj.operator = message.operator;
    }
    if (message.gatewayId !== 0) {
      obj.gatewayId = Math.round(message.gatewayId);
    }
    if (message.payout !== undefined) {
      obj.payout = message.payout;
    }
    if (message.metadata !== undefined) {
      obj.metadata = message.metadata;
    }
    if (message.active !== undefined) {
      obj.active = message.active;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateGateway>, I>>(base?: I): MsgUpdateGateway {
    return MsgUpdateGateway.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateGateway>, I>>(object: I): MsgUpdateGateway {
    const message = createBaseMsgUpdateGateway();
    message.operator = object.operator ?? "";
    message.gatewayId = object.gatewayId ?? 0;
    message.payout = object.payout ?? undefined;
    message.metadata = object.metadata ?? undefined;
    message.active = object.active ?? undefined;
    return message;
  },
};

function createBaseMsgUpdateGatewayResponse(): MsgUpdateGatewayResponse {
  return {};
}

export const MsgUpdateGatewayResponse: MessageFns<MsgUpdateGatewayResponse> = {
  encode(_: MsgUpdateGatewayResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateGatewayResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateGatewayResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateGatewayResponse {
    return {};
  },

  toJSON(_: MsgUpdateGatewayResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateGatewayResponse>, I>>(base?: I): MsgUpdateGatewayResponse {
    return MsgUpdateGatewayResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateGatewayResponse>, I>>(_: I): MsgUpdateGatewayResponse {
    const message = createBaseMsgUpdateGatewayResponse();
    return message;
  },
};

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

function createBaseMsgCreateContract(): MsgCreateContract {
  return {
    client: "",
    gatewayId: 0,
    priceUlmn: 0,
    storageGbPerMonth: 0,
    networkGbPerMonth: 0,
    monthsTotal: 0,
    metadata: "",
  };
}

export const MsgCreateContract: MessageFns<MsgCreateContract> = {
  encode(message: MsgCreateContract, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.client !== "") {
      writer.uint32(10).string(message.client);
    }
    if (message.gatewayId !== 0) {
      writer.uint32(16).uint64(message.gatewayId);
    }
    if (message.priceUlmn !== 0) {
      writer.uint32(24).uint64(message.priceUlmn);
    }
    if (message.storageGbPerMonth !== 0) {
      writer.uint32(32).uint64(message.storageGbPerMonth);
    }
    if (message.networkGbPerMonth !== 0) {
      writer.uint32(40).uint64(message.networkGbPerMonth);
    }
    if (message.monthsTotal !== 0) {
      writer.uint32(48).uint32(message.monthsTotal);
    }
    if (message.metadata !== "") {
      writer.uint32(58).string(message.metadata);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateContract {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreateContract();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.client = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.gatewayId = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.priceUlmn = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.storageGbPerMonth = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.networkGbPerMonth = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.monthsTotal = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.metadata = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCreateContract {
    return {
      client: isSet(object.client) ? globalThis.String(object.client) : "",
      gatewayId: isSet(object.gatewayId) ? globalThis.Number(object.gatewayId) : 0,
      priceUlmn: isSet(object.priceUlmn) ? globalThis.Number(object.priceUlmn) : 0,
      storageGbPerMonth: isSet(object.storageGbPerMonth) ? globalThis.Number(object.storageGbPerMonth) : 0,
      networkGbPerMonth: isSet(object.networkGbPerMonth) ? globalThis.Number(object.networkGbPerMonth) : 0,
      monthsTotal: isSet(object.monthsTotal) ? globalThis.Number(object.monthsTotal) : 0,
      metadata: isSet(object.metadata) ? globalThis.String(object.metadata) : "",
    };
  },

  toJSON(message: MsgCreateContract): unknown {
    const obj: any = {};
    if (message.client !== "") {
      obj.client = message.client;
    }
    if (message.gatewayId !== 0) {
      obj.gatewayId = Math.round(message.gatewayId);
    }
    if (message.priceUlmn !== 0) {
      obj.priceUlmn = Math.round(message.priceUlmn);
    }
    if (message.storageGbPerMonth !== 0) {
      obj.storageGbPerMonth = Math.round(message.storageGbPerMonth);
    }
    if (message.networkGbPerMonth !== 0) {
      obj.networkGbPerMonth = Math.round(message.networkGbPerMonth);
    }
    if (message.monthsTotal !== 0) {
      obj.monthsTotal = Math.round(message.monthsTotal);
    }
    if (message.metadata !== "") {
      obj.metadata = message.metadata;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreateContract>, I>>(base?: I): MsgCreateContract {
    return MsgCreateContract.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateContract>, I>>(object: I): MsgCreateContract {
    const message = createBaseMsgCreateContract();
    message.client = object.client ?? "";
    message.gatewayId = object.gatewayId ?? 0;
    message.priceUlmn = object.priceUlmn ?? 0;
    message.storageGbPerMonth = object.storageGbPerMonth ?? 0;
    message.networkGbPerMonth = object.networkGbPerMonth ?? 0;
    message.monthsTotal = object.monthsTotal ?? 0;
    message.metadata = object.metadata ?? "";
    return message;
  },
};

function createBaseMsgCreateContractResponse(): MsgCreateContractResponse {
  return { contractId: 0 };
}

export const MsgCreateContractResponse: MessageFns<MsgCreateContractResponse> = {
  encode(message: MsgCreateContractResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.contractId !== 0) {
      writer.uint32(8).uint64(message.contractId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateContractResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreateContractResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.contractId = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCreateContractResponse {
    return { contractId: isSet(object.contractId) ? globalThis.Number(object.contractId) : 0 };
  },

  toJSON(message: MsgCreateContractResponse): unknown {
    const obj: any = {};
    if (message.contractId !== 0) {
      obj.contractId = Math.round(message.contractId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreateContractResponse>, I>>(base?: I): MsgCreateContractResponse {
    return MsgCreateContractResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateContractResponse>, I>>(object: I): MsgCreateContractResponse {
    const message = createBaseMsgCreateContractResponse();
    message.contractId = object.contractId ?? 0;
    return message;
  },
};

function createBaseMsgClaimPayment(): MsgClaimPayment {
  return { operator: "", contractId: 0 };
}

export const MsgClaimPayment: MessageFns<MsgClaimPayment> = {
  encode(message: MsgClaimPayment, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.operator !== "") {
      writer.uint32(10).string(message.operator);
    }
    if (message.contractId !== 0) {
      writer.uint32(16).uint64(message.contractId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgClaimPayment {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgClaimPayment();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.operator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.contractId = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgClaimPayment {
    return {
      operator: isSet(object.operator) ? globalThis.String(object.operator) : "",
      contractId: isSet(object.contractId) ? globalThis.Number(object.contractId) : 0,
    };
  },

  toJSON(message: MsgClaimPayment): unknown {
    const obj: any = {};
    if (message.operator !== "") {
      obj.operator = message.operator;
    }
    if (message.contractId !== 0) {
      obj.contractId = Math.round(message.contractId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgClaimPayment>, I>>(base?: I): MsgClaimPayment {
    return MsgClaimPayment.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgClaimPayment>, I>>(object: I): MsgClaimPayment {
    const message = createBaseMsgClaimPayment();
    message.operator = object.operator ?? "";
    message.contractId = object.contractId ?? 0;
    return message;
  },
};

function createBaseMsgClaimPaymentResponse(): MsgClaimPaymentResponse {
  return { paidUlmn: "" };
}

export const MsgClaimPaymentResponse: MessageFns<MsgClaimPaymentResponse> = {
  encode(message: MsgClaimPaymentResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.paidUlmn !== "") {
      writer.uint32(10).string(message.paidUlmn);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgClaimPaymentResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgClaimPaymentResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.paidUlmn = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgClaimPaymentResponse {
    return { paidUlmn: isSet(object.paidUlmn) ? globalThis.String(object.paidUlmn) : "" };
  },

  toJSON(message: MsgClaimPaymentResponse): unknown {
    const obj: any = {};
    if (message.paidUlmn !== "") {
      obj.paidUlmn = message.paidUlmn;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgClaimPaymentResponse>, I>>(base?: I): MsgClaimPaymentResponse {
    return MsgClaimPaymentResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgClaimPaymentResponse>, I>>(object: I): MsgClaimPaymentResponse {
    const message = createBaseMsgClaimPaymentResponse();
    message.paidUlmn = object.paidUlmn ?? "";
    return message;
  },
};

function createBaseMsgCancelContract(): MsgCancelContract {
  return { client: "", contractId: 0 };
}

export const MsgCancelContract: MessageFns<MsgCancelContract> = {
  encode(message: MsgCancelContract, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.client !== "") {
      writer.uint32(10).string(message.client);
    }
    if (message.contractId !== 0) {
      writer.uint32(16).uint64(message.contractId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCancelContract {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCancelContract();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.client = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.contractId = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCancelContract {
    return {
      client: isSet(object.client) ? globalThis.String(object.client) : "",
      contractId: isSet(object.contractId) ? globalThis.Number(object.contractId) : 0,
    };
  },

  toJSON(message: MsgCancelContract): unknown {
    const obj: any = {};
    if (message.client !== "") {
      obj.client = message.client;
    }
    if (message.contractId !== 0) {
      obj.contractId = Math.round(message.contractId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCancelContract>, I>>(base?: I): MsgCancelContract {
    return MsgCancelContract.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCancelContract>, I>>(object: I): MsgCancelContract {
    const message = createBaseMsgCancelContract();
    message.client = object.client ?? "";
    message.contractId = object.contractId ?? 0;
    return message;
  },
};

function createBaseMsgCancelContractResponse(): MsgCancelContractResponse {
  return { refundedUlmn: "" };
}

export const MsgCancelContractResponse: MessageFns<MsgCancelContractResponse> = {
  encode(message: MsgCancelContractResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.refundedUlmn !== "") {
      writer.uint32(10).string(message.refundedUlmn);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCancelContractResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCancelContractResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.refundedUlmn = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCancelContractResponse {
    return { refundedUlmn: isSet(object.refundedUlmn) ? globalThis.String(object.refundedUlmn) : "" };
  },

  toJSON(message: MsgCancelContractResponse): unknown {
    const obj: any = {};
    if (message.refundedUlmn !== "") {
      obj.refundedUlmn = message.refundedUlmn;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCancelContractResponse>, I>>(base?: I): MsgCancelContractResponse {
    return MsgCancelContractResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCancelContractResponse>, I>>(object: I): MsgCancelContractResponse {
    const message = createBaseMsgCancelContractResponse();
    message.refundedUlmn = object.refundedUlmn ?? "";
    return message;
  },
};

function createBaseMsgFinalizeContract(): MsgFinalizeContract {
  return { finalizer: "", contractId: 0 };
}

export const MsgFinalizeContract: MessageFns<MsgFinalizeContract> = {
  encode(message: MsgFinalizeContract, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.finalizer !== "") {
      writer.uint32(10).string(message.finalizer);
    }
    if (message.contractId !== 0) {
      writer.uint32(16).uint64(message.contractId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgFinalizeContract {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgFinalizeContract();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.finalizer = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.contractId = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgFinalizeContract {
    return {
      finalizer: isSet(object.finalizer) ? globalThis.String(object.finalizer) : "",
      contractId: isSet(object.contractId) ? globalThis.Number(object.contractId) : 0,
    };
  },

  toJSON(message: MsgFinalizeContract): unknown {
    const obj: any = {};
    if (message.finalizer !== "") {
      obj.finalizer = message.finalizer;
    }
    if (message.contractId !== 0) {
      obj.contractId = Math.round(message.contractId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgFinalizeContract>, I>>(base?: I): MsgFinalizeContract {
    return MsgFinalizeContract.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgFinalizeContract>, I>>(object: I): MsgFinalizeContract {
    const message = createBaseMsgFinalizeContract();
    message.finalizer = object.finalizer ?? "";
    message.contractId = object.contractId ?? 0;
    return message;
  },
};

function createBaseMsgFinalizeContractResponse(): MsgFinalizeContractResponse {
  return { rewardUlmn: "" };
}

export const MsgFinalizeContractResponse: MessageFns<MsgFinalizeContractResponse> = {
  encode(message: MsgFinalizeContractResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rewardUlmn !== "") {
      writer.uint32(10).string(message.rewardUlmn);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgFinalizeContractResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgFinalizeContractResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.rewardUlmn = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgFinalizeContractResponse {
    return { rewardUlmn: isSet(object.rewardUlmn) ? globalThis.String(object.rewardUlmn) : "" };
  },

  toJSON(message: MsgFinalizeContractResponse): unknown {
    const obj: any = {};
    if (message.rewardUlmn !== "") {
      obj.rewardUlmn = message.rewardUlmn;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgFinalizeContractResponse>, I>>(base?: I): MsgFinalizeContractResponse {
    return MsgFinalizeContractResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgFinalizeContractResponse>, I>>(object: I): MsgFinalizeContractResponse {
    const message = createBaseMsgFinalizeContractResponse();
    message.rewardUlmn = object.rewardUlmn ?? "";
    return message;
  },
};

export interface Msg {
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse>;
  RegisterGateway(request: MsgRegisterGateway): Promise<MsgRegisterGatewayResponse>;
  UpdateGateway(request: MsgUpdateGateway): Promise<MsgUpdateGatewayResponse>;
  CreateContract(request: MsgCreateContract): Promise<MsgCreateContractResponse>;
  ClaimPayment(request: MsgClaimPayment): Promise<MsgClaimPaymentResponse>;
  CancelContract(request: MsgCancelContract): Promise<MsgCancelContractResponse>;
  FinalizeContract(request: MsgFinalizeContract): Promise<MsgFinalizeContractResponse>;
}

export const MsgServiceName = "lumen.gateway.v1.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.UpdateParams = this.UpdateParams.bind(this);
    this.RegisterGateway = this.RegisterGateway.bind(this);
    this.UpdateGateway = this.UpdateGateway.bind(this);
    this.CreateContract = this.CreateContract.bind(this);
    this.ClaimPayment = this.ClaimPayment.bind(this);
    this.CancelContract = this.CancelContract.bind(this);
    this.FinalizeContract = this.FinalizeContract.bind(this);
  }
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse> {
    const data = MsgUpdateParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateParams", data);
    return promise.then((data) => MsgUpdateParamsResponse.decode(new BinaryReader(data)));
  }

  RegisterGateway(request: MsgRegisterGateway): Promise<MsgRegisterGatewayResponse> {
    const data = MsgRegisterGateway.encode(request).finish();
    const promise = this.rpc.request(this.service, "RegisterGateway", data);
    return promise.then((data) => MsgRegisterGatewayResponse.decode(new BinaryReader(data)));
  }

  UpdateGateway(request: MsgUpdateGateway): Promise<MsgUpdateGatewayResponse> {
    const data = MsgUpdateGateway.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateGateway", data);
    return promise.then((data) => MsgUpdateGatewayResponse.decode(new BinaryReader(data)));
  }

  CreateContract(request: MsgCreateContract): Promise<MsgCreateContractResponse> {
    const data = MsgCreateContract.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateContract", data);
    return promise.then((data) => MsgCreateContractResponse.decode(new BinaryReader(data)));
  }

  ClaimPayment(request: MsgClaimPayment): Promise<MsgClaimPaymentResponse> {
    const data = MsgClaimPayment.encode(request).finish();
    const promise = this.rpc.request(this.service, "ClaimPayment", data);
    return promise.then((data) => MsgClaimPaymentResponse.decode(new BinaryReader(data)));
  }

  CancelContract(request: MsgCancelContract): Promise<MsgCancelContractResponse> {
    const data = MsgCancelContract.encode(request).finish();
    const promise = this.rpc.request(this.service, "CancelContract", data);
    return promise.then((data) => MsgCancelContractResponse.decode(new BinaryReader(data)));
  }

  FinalizeContract(request: MsgFinalizeContract): Promise<MsgFinalizeContractResponse> {
    const data = MsgFinalizeContract.encode(request).finish();
    const promise = this.rpc.request(this.service, "FinalizeContract", data);
    return promise.then((data) => MsgFinalizeContractResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
