// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: lumen/dns/v1/params.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "lumen.dns.v1";

export interface Params {
  baseFeeDns: string;
  alpha: string;
  floor: string;
  ceiling: string;
  t: number;
  graceDays: number;
  auctionDays: number;
  transferFeeUlmn: number;
  bidFeeUlmn: number;
  updateRateLimitSeconds: number;
  updatePowDifficulty: number;
  domainTiers: LengthTier[];
  extTiers: LengthTier[];
  minPriceUlmnPerMonth: number;
  /** Flat fee (in ulmn) charged on every MsgUpdate. */
  updateFeeUlmn: number;
}

/**
 * LengthTier defines a multiplier (in basis points) that applies when the
 * domain or extension length is ≤ max_len. The last tier must set max_len = 0
 * to denote an open upper bound.
 */
export interface LengthTier {
  maxLen: number;
  multiplierBps: number;
}

function createBaseParams(): Params {
  return {
    baseFeeDns: "",
    alpha: "",
    floor: "",
    ceiling: "",
    t: 0,
    graceDays: 0,
    auctionDays: 0,
    transferFeeUlmn: 0,
    bidFeeUlmn: 0,
    updateRateLimitSeconds: 0,
    updatePowDifficulty: 0,
    domainTiers: [],
    extTiers: [],
    minPriceUlmnPerMonth: 0,
    updateFeeUlmn: 0,
  };
}

export const Params: MessageFns<Params> = {
  encode(message: Params, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.baseFeeDns !== "") {
      writer.uint32(10).string(message.baseFeeDns);
    }
    if (message.alpha !== "") {
      writer.uint32(18).string(message.alpha);
    }
    if (message.floor !== "") {
      writer.uint32(26).string(message.floor);
    }
    if (message.ceiling !== "") {
      writer.uint32(34).string(message.ceiling);
    }
    if (message.t !== 0) {
      writer.uint32(40).uint64(message.t);
    }
    if (message.graceDays !== 0) {
      writer.uint32(48).uint64(message.graceDays);
    }
    if (message.auctionDays !== 0) {
      writer.uint32(56).uint64(message.auctionDays);
    }
    if (message.transferFeeUlmn !== 0) {
      writer.uint32(96).uint64(message.transferFeeUlmn);
    }
    if (message.bidFeeUlmn !== 0) {
      writer.uint32(104).uint64(message.bidFeeUlmn);
    }
    if (message.updateRateLimitSeconds !== 0) {
      writer.uint32(112).uint64(message.updateRateLimitSeconds);
    }
    if (message.updatePowDifficulty !== 0) {
      writer.uint32(120).uint32(message.updatePowDifficulty);
    }
    for (const v of message.domainTiers) {
      LengthTier.encode(v!, writer.uint32(130).fork()).join();
    }
    for (const v of message.extTiers) {
      LengthTier.encode(v!, writer.uint32(138).fork()).join();
    }
    if (message.minPriceUlmnPerMonth !== 0) {
      writer.uint32(144).uint64(message.minPriceUlmnPerMonth);
    }
    if (message.updateFeeUlmn !== 0) {
      writer.uint32(152).uint64(message.updateFeeUlmn);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Params {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.baseFeeDns = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.alpha = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.floor = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.ceiling = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.t = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.graceDays = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.auctionDays = longToNumber(reader.uint64());
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.transferFeeUlmn = longToNumber(reader.uint64());
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.bidFeeUlmn = longToNumber(reader.uint64());
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.updateRateLimitSeconds = longToNumber(reader.uint64());
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.updatePowDifficulty = reader.uint32();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.domainTiers.push(LengthTier.decode(reader, reader.uint32()));
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.extTiers.push(LengthTier.decode(reader, reader.uint32()));
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.minPriceUlmnPerMonth = longToNumber(reader.uint64());
          continue;
        }
        case 19: {
          if (tag !== 152) {
            break;
          }

          message.updateFeeUlmn = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      baseFeeDns: isSet(object.baseFeeDns) ? globalThis.String(object.baseFeeDns) : "",
      alpha: isSet(object.alpha) ? globalThis.String(object.alpha) : "",
      floor: isSet(object.floor) ? globalThis.String(object.floor) : "",
      ceiling: isSet(object.ceiling) ? globalThis.String(object.ceiling) : "",
      t: isSet(object.t) ? globalThis.Number(object.t) : 0,
      graceDays: isSet(object.graceDays) ? globalThis.Number(object.graceDays) : 0,
      auctionDays: isSet(object.auctionDays) ? globalThis.Number(object.auctionDays) : 0,
      transferFeeUlmn: isSet(object.transferFeeUlmn) ? globalThis.Number(object.transferFeeUlmn) : 0,
      bidFeeUlmn: isSet(object.bidFeeUlmn) ? globalThis.Number(object.bidFeeUlmn) : 0,
      updateRateLimitSeconds: isSet(object.updateRateLimitSeconds)
        ? globalThis.Number(object.updateRateLimitSeconds)
        : 0,
      updatePowDifficulty: isSet(object.updatePowDifficulty) ? globalThis.Number(object.updatePowDifficulty) : 0,
      domainTiers: globalThis.Array.isArray(object?.domainTiers)
        ? object.domainTiers.map((e: any) => LengthTier.fromJSON(e))
        : [],
      extTiers: globalThis.Array.isArray(object?.extTiers)
        ? object.extTiers.map((e: any) => LengthTier.fromJSON(e))
        : [],
      minPriceUlmnPerMonth: isSet(object.minPriceUlmnPerMonth) ? globalThis.Number(object.minPriceUlmnPerMonth) : 0,
      updateFeeUlmn: isSet(object.updateFeeUlmn) ? globalThis.Number(object.updateFeeUlmn) : 0,
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (message.baseFeeDns !== "") {
      obj.baseFeeDns = message.baseFeeDns;
    }
    if (message.alpha !== "") {
      obj.alpha = message.alpha;
    }
    if (message.floor !== "") {
      obj.floor = message.floor;
    }
    if (message.ceiling !== "") {
      obj.ceiling = message.ceiling;
    }
    if (message.t !== 0) {
      obj.t = Math.round(message.t);
    }
    if (message.graceDays !== 0) {
      obj.graceDays = Math.round(message.graceDays);
    }
    if (message.auctionDays !== 0) {
      obj.auctionDays = Math.round(message.auctionDays);
    }
    if (message.transferFeeUlmn !== 0) {
      obj.transferFeeUlmn = Math.round(message.transferFeeUlmn);
    }
    if (message.bidFeeUlmn !== 0) {
      obj.bidFeeUlmn = Math.round(message.bidFeeUlmn);
    }
    if (message.updateRateLimitSeconds !== 0) {
      obj.updateRateLimitSeconds = Math.round(message.updateRateLimitSeconds);
    }
    if (message.updatePowDifficulty !== 0) {
      obj.updatePowDifficulty = Math.round(message.updatePowDifficulty);
    }
    if (message.domainTiers?.length) {
      obj.domainTiers = message.domainTiers.map((e) => LengthTier.toJSON(e));
    }
    if (message.extTiers?.length) {
      obj.extTiers = message.extTiers.map((e) => LengthTier.toJSON(e));
    }
    if (message.minPriceUlmnPerMonth !== 0) {
      obj.minPriceUlmnPerMonth = Math.round(message.minPriceUlmnPerMonth);
    }
    if (message.updateFeeUlmn !== 0) {
      obj.updateFeeUlmn = Math.round(message.updateFeeUlmn);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Params>, I>>(base?: I): Params {
    return Params.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Params>, I>>(object: I): Params {
    const message = createBaseParams();
    message.baseFeeDns = object.baseFeeDns ?? "";
    message.alpha = object.alpha ?? "";
    message.floor = object.floor ?? "";
    message.ceiling = object.ceiling ?? "";
    message.t = object.t ?? 0;
    message.graceDays = object.graceDays ?? 0;
    message.auctionDays = object.auctionDays ?? 0;
    message.transferFeeUlmn = object.transferFeeUlmn ?? 0;
    message.bidFeeUlmn = object.bidFeeUlmn ?? 0;
    message.updateRateLimitSeconds = object.updateRateLimitSeconds ?? 0;
    message.updatePowDifficulty = object.updatePowDifficulty ?? 0;
    message.domainTiers = object.domainTiers?.map((e) => LengthTier.fromPartial(e)) || [];
    message.extTiers = object.extTiers?.map((e) => LengthTier.fromPartial(e)) || [];
    message.minPriceUlmnPerMonth = object.minPriceUlmnPerMonth ?? 0;
    message.updateFeeUlmn = object.updateFeeUlmn ?? 0;
    return message;
  },
};

function createBaseLengthTier(): LengthTier {
  return { maxLen: 0, multiplierBps: 0 };
}

export const LengthTier: MessageFns<LengthTier> = {
  encode(message: LengthTier, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.maxLen !== 0) {
      writer.uint32(8).uint32(message.maxLen);
    }
    if (message.multiplierBps !== 0) {
      writer.uint32(16).uint32(message.multiplierBps);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LengthTier {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLengthTier();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.maxLen = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.multiplierBps = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LengthTier {
    return {
      maxLen: isSet(object.maxLen) ? globalThis.Number(object.maxLen) : 0,
      multiplierBps: isSet(object.multiplierBps) ? globalThis.Number(object.multiplierBps) : 0,
    };
  },

  toJSON(message: LengthTier): unknown {
    const obj: any = {};
    if (message.maxLen !== 0) {
      obj.maxLen = Math.round(message.maxLen);
    }
    if (message.multiplierBps !== 0) {
      obj.multiplierBps = Math.round(message.multiplierBps);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LengthTier>, I>>(base?: I): LengthTier {
    return LengthTier.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LengthTier>, I>>(object: I): LengthTier {
    const message = createBaseLengthTier();
    message.maxLen = object.maxLen ?? 0;
    message.multiplierBps = object.multiplierBps ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
