// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               unknown
// source: lumen/dns/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Record } from "./domain";
import { Params } from "./params";

export const protobufPackage = "lumen.dns.v1";

export interface MsgUpdateParams {
  authority: string;
  params: Params | undefined;
}

export interface MsgUpdateParamsResponse {
}

export interface MsgRegister {
  creator: string;
  domain: string;
  ext: string;
  records: Record[];
  durationDays: number;
  owner: string;
}

export interface MsgRegisterResponse {
}

export interface MsgUpdate {
  creator: string;
  domain: string;
  ext: string;
  records: Record[];
  powNonce: number;
}

export interface MsgUpdateResponse {
}

export interface MsgRenew {
  creator: string;
  domain: string;
  ext: string;
  durationDays: number;
}

export interface MsgRenewResponse {
}

export interface MsgTransfer {
  creator: string;
  domain: string;
  ext: string;
  newOwner: string;
}

export interface MsgTransferResponse {
}

export interface MsgBid {
  creator: string;
  domain: string;
  ext: string;
  amount: string;
}

export interface MsgBidResponse {
}

export interface MsgCreateDomain {
  creator: string;
  index: string;
  name: string;
  owner: string;
  records: Record[];
  expireAt: number;
}

export interface MsgCreateDomainResponse {
}

export interface MsgUpdateDomain {
  creator: string;
  index: string;
  name: string;
  owner: string;
  records: Record[];
  expireAt: number;
  powNonce: number;
}

export interface MsgUpdateDomainResponse {
}

export interface MsgDeleteDomain {
  creator: string;
  index: string;
}

export interface MsgDeleteDomainResponse {
}

export interface MsgCreateAuction {
  creator: string;
  index: string;
  name: string;
  start: number;
  end: number;
  highestBid: string;
  bidder: string;
}

export interface MsgCreateAuctionResponse {
}

export interface MsgUpdateAuction {
  creator: string;
  index: string;
  name: string;
  start: number;
  end: number;
  highestBid: string;
  bidder: string;
}

export interface MsgUpdateAuctionResponse {
}

export interface MsgDeleteAuction {
  creator: string;
  index: string;
}

export interface MsgDeleteAuctionResponse {
}

export interface MsgSettle {
  creator: string;
  domain: string;
  ext: string;
}

export interface MsgSettleResponse {
}

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

function createBaseMsgRegister(): MsgRegister {
  return { creator: "", domain: "", ext: "", records: [], durationDays: 0, owner: "" };
}

export const MsgRegister: MessageFns<MsgRegister> = {
  encode(message: MsgRegister, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.domain !== "") {
      writer.uint32(18).string(message.domain);
    }
    if (message.ext !== "") {
      writer.uint32(26).string(message.ext);
    }
    for (const v of message.records) {
      Record.encode(v!, writer.uint32(50).fork()).join();
    }
    if (message.durationDays !== 0) {
      writer.uint32(56).uint64(message.durationDays);
    }
    if (message.owner !== "") {
      writer.uint32(74).string(message.owner);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRegister {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRegister();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ext = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.records.push(Record.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.durationDays = longToNumber(reader.uint64());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.owner = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRegister {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      domain: isSet(object.domain) ? globalThis.String(object.domain) : "",
      ext: isSet(object.ext) ? globalThis.String(object.ext) : "",
      records: globalThis.Array.isArray(object?.records) ? object.records.map((e: any) => Record.fromJSON(e)) : [],
      durationDays: isSet(object.durationDays)
        ? globalThis.Number(object.durationDays)
        : isSet(object.duration_days)
        ? globalThis.Number(object.duration_days)
        : 0,
      owner: isSet(object.owner) ? globalThis.String(object.owner) : "",
    };
  },

  toJSON(message: MsgRegister): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.domain !== "") {
      obj.domain = message.domain;
    }
    if (message.ext !== "") {
      obj.ext = message.ext;
    }
    if (message.records?.length) {
      obj.records = message.records.map((e) => Record.toJSON(e));
    }
    if (message.durationDays !== 0) {
      obj.durationDays = Math.round(message.durationDays);
    }
    if (message.owner !== "") {
      obj.owner = message.owner;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegister>, I>>(base?: I): MsgRegister {
    return MsgRegister.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegister>, I>>(object: I): MsgRegister {
    const message = createBaseMsgRegister();
    message.creator = object.creator ?? "";
    message.domain = object.domain ?? "";
    message.ext = object.ext ?? "";
    message.records = object.records?.map((e) => Record.fromPartial(e)) || [];
    message.durationDays = object.durationDays ?? 0;
    message.owner = object.owner ?? "";
    return message;
  },
};

function createBaseMsgRegisterResponse(): MsgRegisterResponse {
  return {};
}

export const MsgRegisterResponse: MessageFns<MsgRegisterResponse> = {
  encode(_: MsgRegisterResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRegisterResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRegisterResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgRegisterResponse {
    return {};
  },

  toJSON(_: MsgRegisterResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegisterResponse>, I>>(base?: I): MsgRegisterResponse {
    return MsgRegisterResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegisterResponse>, I>>(_: I): MsgRegisterResponse {
    const message = createBaseMsgRegisterResponse();
    return message;
  },
};

function createBaseMsgUpdate(): MsgUpdate {
  return { creator: "", domain: "", ext: "", records: [], powNonce: 0 };
}

export const MsgUpdate: MessageFns<MsgUpdate> = {
  encode(message: MsgUpdate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.domain !== "") {
      writer.uint32(18).string(message.domain);
    }
    if (message.ext !== "") {
      writer.uint32(26).string(message.ext);
    }
    for (const v of message.records) {
      Record.encode(v!, writer.uint32(50).fork()).join();
    }
    if (message.powNonce !== 0) {
      writer.uint32(56).uint64(message.powNonce);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ext = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.records.push(Record.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.powNonce = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdate {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      domain: isSet(object.domain) ? globalThis.String(object.domain) : "",
      ext: isSet(object.ext) ? globalThis.String(object.ext) : "",
      records: globalThis.Array.isArray(object?.records) ? object.records.map((e: any) => Record.fromJSON(e)) : [],
      powNonce: isSet(object.powNonce)
        ? globalThis.Number(object.powNonce)
        : isSet(object.pow_nonce)
        ? globalThis.Number(object.pow_nonce)
        : 0,
    };
  },

  toJSON(message: MsgUpdate): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.domain !== "") {
      obj.domain = message.domain;
    }
    if (message.ext !== "") {
      obj.ext = message.ext;
    }
    if (message.records?.length) {
      obj.records = message.records.map((e) => Record.toJSON(e));
    }
    if (message.powNonce !== 0) {
      obj.powNonce = Math.round(message.powNonce);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdate>, I>>(base?: I): MsgUpdate {
    return MsgUpdate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdate>, I>>(object: I): MsgUpdate {
    const message = createBaseMsgUpdate();
    message.creator = object.creator ?? "";
    message.domain = object.domain ?? "";
    message.ext = object.ext ?? "";
    message.records = object.records?.map((e) => Record.fromPartial(e)) || [];
    message.powNonce = object.powNonce ?? 0;
    return message;
  },
};

function createBaseMsgUpdateResponse(): MsgUpdateResponse {
  return {};
}

export const MsgUpdateResponse: MessageFns<MsgUpdateResponse> = {
  encode(_: MsgUpdateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateResponse {
    return {};
  },

  toJSON(_: MsgUpdateResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateResponse>, I>>(base?: I): MsgUpdateResponse {
    return MsgUpdateResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateResponse>, I>>(_: I): MsgUpdateResponse {
    const message = createBaseMsgUpdateResponse();
    return message;
  },
};

function createBaseMsgRenew(): MsgRenew {
  return { creator: "", domain: "", ext: "", durationDays: 0 };
}

export const MsgRenew: MessageFns<MsgRenew> = {
  encode(message: MsgRenew, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.domain !== "") {
      writer.uint32(18).string(message.domain);
    }
    if (message.ext !== "") {
      writer.uint32(26).string(message.ext);
    }
    if (message.durationDays !== 0) {
      writer.uint32(32).uint64(message.durationDays);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRenew {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRenew();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ext = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.durationDays = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRenew {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      domain: isSet(object.domain) ? globalThis.String(object.domain) : "",
      ext: isSet(object.ext) ? globalThis.String(object.ext) : "",
      durationDays: isSet(object.durationDays)
        ? globalThis.Number(object.durationDays)
        : isSet(object.duration_days)
        ? globalThis.Number(object.duration_days)
        : 0,
    };
  },

  toJSON(message: MsgRenew): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.domain !== "") {
      obj.domain = message.domain;
    }
    if (message.ext !== "") {
      obj.ext = message.ext;
    }
    if (message.durationDays !== 0) {
      obj.durationDays = Math.round(message.durationDays);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRenew>, I>>(base?: I): MsgRenew {
    return MsgRenew.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRenew>, I>>(object: I): MsgRenew {
    const message = createBaseMsgRenew();
    message.creator = object.creator ?? "";
    message.domain = object.domain ?? "";
    message.ext = object.ext ?? "";
    message.durationDays = object.durationDays ?? 0;
    return message;
  },
};

function createBaseMsgRenewResponse(): MsgRenewResponse {
  return {};
}

export const MsgRenewResponse: MessageFns<MsgRenewResponse> = {
  encode(_: MsgRenewResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRenewResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRenewResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgRenewResponse {
    return {};
  },

  toJSON(_: MsgRenewResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRenewResponse>, I>>(base?: I): MsgRenewResponse {
    return MsgRenewResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRenewResponse>, I>>(_: I): MsgRenewResponse {
    const message = createBaseMsgRenewResponse();
    return message;
  },
};

function createBaseMsgTransfer(): MsgTransfer {
  return { creator: "", domain: "", ext: "", newOwner: "" };
}

export const MsgTransfer: MessageFns<MsgTransfer> = {
  encode(message: MsgTransfer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.domain !== "") {
      writer.uint32(18).string(message.domain);
    }
    if (message.ext !== "") {
      writer.uint32(26).string(message.ext);
    }
    if (message.newOwner !== "") {
      writer.uint32(34).string(message.newOwner);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgTransfer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgTransfer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ext = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.newOwner = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgTransfer {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      domain: isSet(object.domain) ? globalThis.String(object.domain) : "",
      ext: isSet(object.ext) ? globalThis.String(object.ext) : "",
      newOwner: isSet(object.newOwner)
        ? globalThis.String(object.newOwner)
        : isSet(object.new_owner)
        ? globalThis.String(object.new_owner)
        : "",
    };
  },

  toJSON(message: MsgTransfer): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.domain !== "") {
      obj.domain = message.domain;
    }
    if (message.ext !== "") {
      obj.ext = message.ext;
    }
    if (message.newOwner !== "") {
      obj.newOwner = message.newOwner;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgTransfer>, I>>(base?: I): MsgTransfer {
    return MsgTransfer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgTransfer>, I>>(object: I): MsgTransfer {
    const message = createBaseMsgTransfer();
    message.creator = object.creator ?? "";
    message.domain = object.domain ?? "";
    message.ext = object.ext ?? "";
    message.newOwner = object.newOwner ?? "";
    return message;
  },
};

function createBaseMsgTransferResponse(): MsgTransferResponse {
  return {};
}

export const MsgTransferResponse: MessageFns<MsgTransferResponse> = {
  encode(_: MsgTransferResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgTransferResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgTransferResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgTransferResponse {
    return {};
  },

  toJSON(_: MsgTransferResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgTransferResponse>, I>>(base?: I): MsgTransferResponse {
    return MsgTransferResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgTransferResponse>, I>>(_: I): MsgTransferResponse {
    const message = createBaseMsgTransferResponse();
    return message;
  },
};

function createBaseMsgBid(): MsgBid {
  return { creator: "", domain: "", ext: "", amount: "" };
}

export const MsgBid: MessageFns<MsgBid> = {
  encode(message: MsgBid, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.domain !== "") {
      writer.uint32(18).string(message.domain);
    }
    if (message.ext !== "") {
      writer.uint32(26).string(message.ext);
    }
    if (message.amount !== "") {
      writer.uint32(34).string(message.amount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgBid {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgBid();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ext = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgBid {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      domain: isSet(object.domain) ? globalThis.String(object.domain) : "",
      ext: isSet(object.ext) ? globalThis.String(object.ext) : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
    };
  },

  toJSON(message: MsgBid): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.domain !== "") {
      obj.domain = message.domain;
    }
    if (message.ext !== "") {
      obj.ext = message.ext;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgBid>, I>>(base?: I): MsgBid {
    return MsgBid.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgBid>, I>>(object: I): MsgBid {
    const message = createBaseMsgBid();
    message.creator = object.creator ?? "";
    message.domain = object.domain ?? "";
    message.ext = object.ext ?? "";
    message.amount = object.amount ?? "";
    return message;
  },
};

function createBaseMsgBidResponse(): MsgBidResponse {
  return {};
}

export const MsgBidResponse: MessageFns<MsgBidResponse> = {
  encode(_: MsgBidResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgBidResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgBidResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgBidResponse {
    return {};
  },

  toJSON(_: MsgBidResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgBidResponse>, I>>(base?: I): MsgBidResponse {
    return MsgBidResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgBidResponse>, I>>(_: I): MsgBidResponse {
    const message = createBaseMsgBidResponse();
    return message;
  },
};

function createBaseMsgCreateDomain(): MsgCreateDomain {
  return { creator: "", index: "", name: "", owner: "", records: [], expireAt: 0 };
}

export const MsgCreateDomain: MessageFns<MsgCreateDomain> = {
  encode(message: MsgCreateDomain, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.index !== "") {
      writer.uint32(18).string(message.index);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.owner !== "") {
      writer.uint32(34).string(message.owner);
    }
    for (const v of message.records) {
      Record.encode(v!, writer.uint32(42).fork()).join();
    }
    if (message.expireAt !== 0) {
      writer.uint32(48).uint64(message.expireAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateDomain {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreateDomain();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.index = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.owner = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.records.push(Record.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.expireAt = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCreateDomain {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      index: isSet(object.index) ? globalThis.String(object.index) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      owner: isSet(object.owner) ? globalThis.String(object.owner) : "",
      records: globalThis.Array.isArray(object?.records) ? object.records.map((e: any) => Record.fromJSON(e)) : [],
      expireAt: isSet(object.expireAt)
        ? globalThis.Number(object.expireAt)
        : isSet(object.expire_at)
        ? globalThis.Number(object.expire_at)
        : 0,
    };
  },

  toJSON(message: MsgCreateDomain): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.index !== "") {
      obj.index = message.index;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.owner !== "") {
      obj.owner = message.owner;
    }
    if (message.records?.length) {
      obj.records = message.records.map((e) => Record.toJSON(e));
    }
    if (message.expireAt !== 0) {
      obj.expireAt = Math.round(message.expireAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreateDomain>, I>>(base?: I): MsgCreateDomain {
    return MsgCreateDomain.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateDomain>, I>>(object: I): MsgCreateDomain {
    const message = createBaseMsgCreateDomain();
    message.creator = object.creator ?? "";
    message.index = object.index ?? "";
    message.name = object.name ?? "";
    message.owner = object.owner ?? "";
    message.records = object.records?.map((e) => Record.fromPartial(e)) || [];
    message.expireAt = object.expireAt ?? 0;
    return message;
  },
};

function createBaseMsgCreateDomainResponse(): MsgCreateDomainResponse {
  return {};
}

export const MsgCreateDomainResponse: MessageFns<MsgCreateDomainResponse> = {
  encode(_: MsgCreateDomainResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateDomainResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreateDomainResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgCreateDomainResponse {
    return {};
  },

  toJSON(_: MsgCreateDomainResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreateDomainResponse>, I>>(base?: I): MsgCreateDomainResponse {
    return MsgCreateDomainResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateDomainResponse>, I>>(_: I): MsgCreateDomainResponse {
    const message = createBaseMsgCreateDomainResponse();
    return message;
  },
};

function createBaseMsgUpdateDomain(): MsgUpdateDomain {
  return { creator: "", index: "", name: "", owner: "", records: [], expireAt: 0, powNonce: 0 };
}

export const MsgUpdateDomain: MessageFns<MsgUpdateDomain> = {
  encode(message: MsgUpdateDomain, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.index !== "") {
      writer.uint32(18).string(message.index);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.owner !== "") {
      writer.uint32(34).string(message.owner);
    }
    for (const v of message.records) {
      Record.encode(v!, writer.uint32(42).fork()).join();
    }
    if (message.expireAt !== 0) {
      writer.uint32(48).uint64(message.expireAt);
    }
    if (message.powNonce !== 0) {
      writer.uint32(56).uint64(message.powNonce);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateDomain {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateDomain();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.index = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.owner = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.records.push(Record.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.expireAt = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.powNonce = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateDomain {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      index: isSet(object.index) ? globalThis.String(object.index) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      owner: isSet(object.owner) ? globalThis.String(object.owner) : "",
      records: globalThis.Array.isArray(object?.records) ? object.records.map((e: any) => Record.fromJSON(e)) : [],
      expireAt: isSet(object.expireAt)
        ? globalThis.Number(object.expireAt)
        : isSet(object.expire_at)
        ? globalThis.Number(object.expire_at)
        : 0,
      powNonce: isSet(object.powNonce)
        ? globalThis.Number(object.powNonce)
        : isSet(object.pow_nonce)
        ? globalThis.Number(object.pow_nonce)
        : 0,
    };
  },

  toJSON(message: MsgUpdateDomain): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.index !== "") {
      obj.index = message.index;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.owner !== "") {
      obj.owner = message.owner;
    }
    if (message.records?.length) {
      obj.records = message.records.map((e) => Record.toJSON(e));
    }
    if (message.expireAt !== 0) {
      obj.expireAt = Math.round(message.expireAt);
    }
    if (message.powNonce !== 0) {
      obj.powNonce = Math.round(message.powNonce);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateDomain>, I>>(base?: I): MsgUpdateDomain {
    return MsgUpdateDomain.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateDomain>, I>>(object: I): MsgUpdateDomain {
    const message = createBaseMsgUpdateDomain();
    message.creator = object.creator ?? "";
    message.index = object.index ?? "";
    message.name = object.name ?? "";
    message.owner = object.owner ?? "";
    message.records = object.records?.map((e) => Record.fromPartial(e)) || [];
    message.expireAt = object.expireAt ?? 0;
    message.powNonce = object.powNonce ?? 0;
    return message;
  },
};

function createBaseMsgUpdateDomainResponse(): MsgUpdateDomainResponse {
  return {};
}

export const MsgUpdateDomainResponse: MessageFns<MsgUpdateDomainResponse> = {
  encode(_: MsgUpdateDomainResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateDomainResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateDomainResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateDomainResponse {
    return {};
  },

  toJSON(_: MsgUpdateDomainResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateDomainResponse>, I>>(base?: I): MsgUpdateDomainResponse {
    return MsgUpdateDomainResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateDomainResponse>, I>>(_: I): MsgUpdateDomainResponse {
    const message = createBaseMsgUpdateDomainResponse();
    return message;
  },
};

function createBaseMsgDeleteDomain(): MsgDeleteDomain {
  return { creator: "", index: "" };
}

export const MsgDeleteDomain: MessageFns<MsgDeleteDomain> = {
  encode(message: MsgDeleteDomain, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.index !== "") {
      writer.uint32(18).string(message.index);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgDeleteDomain {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgDeleteDomain();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.index = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgDeleteDomain {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      index: isSet(object.index) ? globalThis.String(object.index) : "",
    };
  },

  toJSON(message: MsgDeleteDomain): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.index !== "") {
      obj.index = message.index;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgDeleteDomain>, I>>(base?: I): MsgDeleteDomain {
    return MsgDeleteDomain.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgDeleteDomain>, I>>(object: I): MsgDeleteDomain {
    const message = createBaseMsgDeleteDomain();
    message.creator = object.creator ?? "";
    message.index = object.index ?? "";
    return message;
  },
};

function createBaseMsgDeleteDomainResponse(): MsgDeleteDomainResponse {
  return {};
}

export const MsgDeleteDomainResponse: MessageFns<MsgDeleteDomainResponse> = {
  encode(_: MsgDeleteDomainResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgDeleteDomainResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgDeleteDomainResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgDeleteDomainResponse {
    return {};
  },

  toJSON(_: MsgDeleteDomainResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgDeleteDomainResponse>, I>>(base?: I): MsgDeleteDomainResponse {
    return MsgDeleteDomainResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgDeleteDomainResponse>, I>>(_: I): MsgDeleteDomainResponse {
    const message = createBaseMsgDeleteDomainResponse();
    return message;
  },
};

function createBaseMsgCreateAuction(): MsgCreateAuction {
  return { creator: "", index: "", name: "", start: 0, end: 0, highestBid: "", bidder: "" };
}

export const MsgCreateAuction: MessageFns<MsgCreateAuction> = {
  encode(message: MsgCreateAuction, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.index !== "") {
      writer.uint32(18).string(message.index);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.start !== 0) {
      writer.uint32(32).uint64(message.start);
    }
    if (message.end !== 0) {
      writer.uint32(40).uint64(message.end);
    }
    if (message.highestBid !== "") {
      writer.uint32(50).string(message.highestBid);
    }
    if (message.bidder !== "") {
      writer.uint32(58).string(message.bidder);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateAuction {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreateAuction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.index = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.start = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.end = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.highestBid = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.bidder = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCreateAuction {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      index: isSet(object.index) ? globalThis.String(object.index) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      start: isSet(object.start) ? globalThis.Number(object.start) : 0,
      end: isSet(object.end) ? globalThis.Number(object.end) : 0,
      highestBid: isSet(object.highestBid)
        ? globalThis.String(object.highestBid)
        : isSet(object.highest_bid)
        ? globalThis.String(object.highest_bid)
        : "",
      bidder: isSet(object.bidder) ? globalThis.String(object.bidder) : "",
    };
  },

  toJSON(message: MsgCreateAuction): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.index !== "") {
      obj.index = message.index;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.start !== 0) {
      obj.start = Math.round(message.start);
    }
    if (message.end !== 0) {
      obj.end = Math.round(message.end);
    }
    if (message.highestBid !== "") {
      obj.highestBid = message.highestBid;
    }
    if (message.bidder !== "") {
      obj.bidder = message.bidder;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreateAuction>, I>>(base?: I): MsgCreateAuction {
    return MsgCreateAuction.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateAuction>, I>>(object: I): MsgCreateAuction {
    const message = createBaseMsgCreateAuction();
    message.creator = object.creator ?? "";
    message.index = object.index ?? "";
    message.name = object.name ?? "";
    message.start = object.start ?? 0;
    message.end = object.end ?? 0;
    message.highestBid = object.highestBid ?? "";
    message.bidder = object.bidder ?? "";
    return message;
  },
};

function createBaseMsgCreateAuctionResponse(): MsgCreateAuctionResponse {
  return {};
}

export const MsgCreateAuctionResponse: MessageFns<MsgCreateAuctionResponse> = {
  encode(_: MsgCreateAuctionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateAuctionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreateAuctionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgCreateAuctionResponse {
    return {};
  },

  toJSON(_: MsgCreateAuctionResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreateAuctionResponse>, I>>(base?: I): MsgCreateAuctionResponse {
    return MsgCreateAuctionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateAuctionResponse>, I>>(_: I): MsgCreateAuctionResponse {
    const message = createBaseMsgCreateAuctionResponse();
    return message;
  },
};

function createBaseMsgUpdateAuction(): MsgUpdateAuction {
  return { creator: "", index: "", name: "", start: 0, end: 0, highestBid: "", bidder: "" };
}

export const MsgUpdateAuction: MessageFns<MsgUpdateAuction> = {
  encode(message: MsgUpdateAuction, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.index !== "") {
      writer.uint32(18).string(message.index);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.start !== 0) {
      writer.uint32(32).uint64(message.start);
    }
    if (message.end !== 0) {
      writer.uint32(40).uint64(message.end);
    }
    if (message.highestBid !== "") {
      writer.uint32(50).string(message.highestBid);
    }
    if (message.bidder !== "") {
      writer.uint32(58).string(message.bidder);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateAuction {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateAuction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.index = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.start = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.end = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.highestBid = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.bidder = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateAuction {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      index: isSet(object.index) ? globalThis.String(object.index) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      start: isSet(object.start) ? globalThis.Number(object.start) : 0,
      end: isSet(object.end) ? globalThis.Number(object.end) : 0,
      highestBid: isSet(object.highestBid)
        ? globalThis.String(object.highestBid)
        : isSet(object.highest_bid)
        ? globalThis.String(object.highest_bid)
        : "",
      bidder: isSet(object.bidder) ? globalThis.String(object.bidder) : "",
    };
  },

  toJSON(message: MsgUpdateAuction): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.index !== "") {
      obj.index = message.index;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.start !== 0) {
      obj.start = Math.round(message.start);
    }
    if (message.end !== 0) {
      obj.end = Math.round(message.end);
    }
    if (message.highestBid !== "") {
      obj.highestBid = message.highestBid;
    }
    if (message.bidder !== "") {
      obj.bidder = message.bidder;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateAuction>, I>>(base?: I): MsgUpdateAuction {
    return MsgUpdateAuction.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateAuction>, I>>(object: I): MsgUpdateAuction {
    const message = createBaseMsgUpdateAuction();
    message.creator = object.creator ?? "";
    message.index = object.index ?? "";
    message.name = object.name ?? "";
    message.start = object.start ?? 0;
    message.end = object.end ?? 0;
    message.highestBid = object.highestBid ?? "";
    message.bidder = object.bidder ?? "";
    return message;
  },
};

function createBaseMsgUpdateAuctionResponse(): MsgUpdateAuctionResponse {
  return {};
}

export const MsgUpdateAuctionResponse: MessageFns<MsgUpdateAuctionResponse> = {
  encode(_: MsgUpdateAuctionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateAuctionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateAuctionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateAuctionResponse {
    return {};
  },

  toJSON(_: MsgUpdateAuctionResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateAuctionResponse>, I>>(base?: I): MsgUpdateAuctionResponse {
    return MsgUpdateAuctionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateAuctionResponse>, I>>(_: I): MsgUpdateAuctionResponse {
    const message = createBaseMsgUpdateAuctionResponse();
    return message;
  },
};

function createBaseMsgDeleteAuction(): MsgDeleteAuction {
  return { creator: "", index: "" };
}

export const MsgDeleteAuction: MessageFns<MsgDeleteAuction> = {
  encode(message: MsgDeleteAuction, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.index !== "") {
      writer.uint32(18).string(message.index);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgDeleteAuction {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgDeleteAuction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.index = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgDeleteAuction {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      index: isSet(object.index) ? globalThis.String(object.index) : "",
    };
  },

  toJSON(message: MsgDeleteAuction): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.index !== "") {
      obj.index = message.index;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgDeleteAuction>, I>>(base?: I): MsgDeleteAuction {
    return MsgDeleteAuction.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgDeleteAuction>, I>>(object: I): MsgDeleteAuction {
    const message = createBaseMsgDeleteAuction();
    message.creator = object.creator ?? "";
    message.index = object.index ?? "";
    return message;
  },
};

function createBaseMsgDeleteAuctionResponse(): MsgDeleteAuctionResponse {
  return {};
}

export const MsgDeleteAuctionResponse: MessageFns<MsgDeleteAuctionResponse> = {
  encode(_: MsgDeleteAuctionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgDeleteAuctionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgDeleteAuctionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgDeleteAuctionResponse {
    return {};
  },

  toJSON(_: MsgDeleteAuctionResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgDeleteAuctionResponse>, I>>(base?: I): MsgDeleteAuctionResponse {
    return MsgDeleteAuctionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgDeleteAuctionResponse>, I>>(_: I): MsgDeleteAuctionResponse {
    const message = createBaseMsgDeleteAuctionResponse();
    return message;
  },
};

function createBaseMsgSettle(): MsgSettle {
  return { creator: "", domain: "", ext: "" };
}

export const MsgSettle: MessageFns<MsgSettle> = {
  encode(message: MsgSettle, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.domain !== "") {
      writer.uint32(18).string(message.domain);
    }
    if (message.ext !== "") {
      writer.uint32(26).string(message.ext);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSettle {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSettle();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ext = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSettle {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      domain: isSet(object.domain) ? globalThis.String(object.domain) : "",
      ext: isSet(object.ext) ? globalThis.String(object.ext) : "",
    };
  },

  toJSON(message: MsgSettle): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.domain !== "") {
      obj.domain = message.domain;
    }
    if (message.ext !== "") {
      obj.ext = message.ext;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSettle>, I>>(base?: I): MsgSettle {
    return MsgSettle.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSettle>, I>>(object: I): MsgSettle {
    const message = createBaseMsgSettle();
    message.creator = object.creator ?? "";
    message.domain = object.domain ?? "";
    message.ext = object.ext ?? "";
    return message;
  },
};

function createBaseMsgSettleResponse(): MsgSettleResponse {
  return {};
}

export const MsgSettleResponse: MessageFns<MsgSettleResponse> = {
  encode(_: MsgSettleResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSettleResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSettleResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgSettleResponse {
    return {};
  },

  toJSON(_: MsgSettleResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSettleResponse>, I>>(base?: I): MsgSettleResponse {
    return MsgSettleResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSettleResponse>, I>>(_: I): MsgSettleResponse {
    const message = createBaseMsgSettleResponse();
    return message;
  },
};

export interface Msg {
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse>;
  Register(request: MsgRegister): Promise<MsgRegisterResponse>;
  Update(request: MsgUpdate): Promise<MsgUpdateResponse>;
  Renew(request: MsgRenew): Promise<MsgRenewResponse>;
  Transfer(request: MsgTransfer): Promise<MsgTransferResponse>;
  Bid(request: MsgBid): Promise<MsgBidResponse>;
  Settle(request: MsgSettle): Promise<MsgSettleResponse>;
  CreateDomain(request: MsgCreateDomain): Promise<MsgCreateDomainResponse>;
  UpdateDomain(request: MsgUpdateDomain): Promise<MsgUpdateDomainResponse>;
  DeleteDomain(request: MsgDeleteDomain): Promise<MsgDeleteDomainResponse>;
  CreateAuction(request: MsgCreateAuction): Promise<MsgCreateAuctionResponse>;
  UpdateAuction(request: MsgUpdateAuction): Promise<MsgUpdateAuctionResponse>;
  DeleteAuction(request: MsgDeleteAuction): Promise<MsgDeleteAuctionResponse>;
}

export const MsgServiceName = "lumen.dns.v1.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.UpdateParams = this.UpdateParams.bind(this);
    this.Register = this.Register.bind(this);
    this.Update = this.Update.bind(this);
    this.Renew = this.Renew.bind(this);
    this.Transfer = this.Transfer.bind(this);
    this.Bid = this.Bid.bind(this);
    this.Settle = this.Settle.bind(this);
    this.CreateDomain = this.CreateDomain.bind(this);
    this.UpdateDomain = this.UpdateDomain.bind(this);
    this.DeleteDomain = this.DeleteDomain.bind(this);
    this.CreateAuction = this.CreateAuction.bind(this);
    this.UpdateAuction = this.UpdateAuction.bind(this);
    this.DeleteAuction = this.DeleteAuction.bind(this);
  }
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse> {
    const data = MsgUpdateParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateParams", data);
    return promise.then((data) => MsgUpdateParamsResponse.decode(new BinaryReader(data)));
  }

  Register(request: MsgRegister): Promise<MsgRegisterResponse> {
    const data = MsgRegister.encode(request).finish();
    const promise = this.rpc.request(this.service, "Register", data);
    return promise.then((data) => MsgRegisterResponse.decode(new BinaryReader(data)));
  }

  Update(request: MsgUpdate): Promise<MsgUpdateResponse> {
    const data = MsgUpdate.encode(request).finish();
    const promise = this.rpc.request(this.service, "Update", data);
    return promise.then((data) => MsgUpdateResponse.decode(new BinaryReader(data)));
  }

  Renew(request: MsgRenew): Promise<MsgRenewResponse> {
    const data = MsgRenew.encode(request).finish();
    const promise = this.rpc.request(this.service, "Renew", data);
    return promise.then((data) => MsgRenewResponse.decode(new BinaryReader(data)));
  }

  Transfer(request: MsgTransfer): Promise<MsgTransferResponse> {
    const data = MsgTransfer.encode(request).finish();
    const promise = this.rpc.request(this.service, "Transfer", data);
    return promise.then((data) => MsgTransferResponse.decode(new BinaryReader(data)));
  }

  Bid(request: MsgBid): Promise<MsgBidResponse> {
    const data = MsgBid.encode(request).finish();
    const promise = this.rpc.request(this.service, "Bid", data);
    return promise.then((data) => MsgBidResponse.decode(new BinaryReader(data)));
  }

  Settle(request: MsgSettle): Promise<MsgSettleResponse> {
    const data = MsgSettle.encode(request).finish();
    const promise = this.rpc.request(this.service, "Settle", data);
    return promise.then((data) => MsgSettleResponse.decode(new BinaryReader(data)));
  }

  CreateDomain(request: MsgCreateDomain): Promise<MsgCreateDomainResponse> {
    const data = MsgCreateDomain.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateDomain", data);
    return promise.then((data) => MsgCreateDomainResponse.decode(new BinaryReader(data)));
  }

  UpdateDomain(request: MsgUpdateDomain): Promise<MsgUpdateDomainResponse> {
    const data = MsgUpdateDomain.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateDomain", data);
    return promise.then((data) => MsgUpdateDomainResponse.decode(new BinaryReader(data)));
  }

  DeleteDomain(request: MsgDeleteDomain): Promise<MsgDeleteDomainResponse> {
    const data = MsgDeleteDomain.encode(request).finish();
    const promise = this.rpc.request(this.service, "DeleteDomain", data);
    return promise.then((data) => MsgDeleteDomainResponse.decode(new BinaryReader(data)));
  }

  CreateAuction(request: MsgCreateAuction): Promise<MsgCreateAuctionResponse> {
    const data = MsgCreateAuction.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateAuction", data);
    return promise.then((data) => MsgCreateAuctionResponse.decode(new BinaryReader(data)));
  }

  UpdateAuction(request: MsgUpdateAuction): Promise<MsgUpdateAuctionResponse> {
    const data = MsgUpdateAuction.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateAuction", data);
    return promise.then((data) => MsgUpdateAuctionResponse.decode(new BinaryReader(data)));
  }

  DeleteAuction(request: MsgDeleteAuction): Promise<MsgDeleteAuctionResponse> {
    const data = MsgDeleteAuction.encode(request).finish();
    const promise = this.rpc.request(this.service, "DeleteAuction", data);
    return promise.then((data) => MsgDeleteAuctionResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
