// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               unknown
// source: lumen/tokenomics/v1/params.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "lumen.tokenomics.v1";

export interface Params {
  txTaxRate: string;
  initialRewardPerBlockLumn: number;
  halvingIntervalBlocks: number;
  supplyCapLumn: number;
  decimals: number;
  minSendUlmn: number;
  denom: string;
  distributionIntervalBlocks: number;
}

function createBaseParams(): Params {
  return {
    txTaxRate: "",
    initialRewardPerBlockLumn: 0,
    halvingIntervalBlocks: 0,
    supplyCapLumn: 0,
    decimals: 0,
    minSendUlmn: 0,
    denom: "",
    distributionIntervalBlocks: 0,
  };
}

export const Params: MessageFns<Params> = {
  encode(message: Params, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.txTaxRate !== "") {
      writer.uint32(10).string(message.txTaxRate);
    }
    if (message.initialRewardPerBlockLumn !== 0) {
      writer.uint32(16).uint64(message.initialRewardPerBlockLumn);
    }
    if (message.halvingIntervalBlocks !== 0) {
      writer.uint32(24).uint64(message.halvingIntervalBlocks);
    }
    if (message.supplyCapLumn !== 0) {
      writer.uint32(32).uint64(message.supplyCapLumn);
    }
    if (message.decimals !== 0) {
      writer.uint32(40).uint32(message.decimals);
    }
    if (message.minSendUlmn !== 0) {
      writer.uint32(48).uint64(message.minSendUlmn);
    }
    if (message.denom !== "") {
      writer.uint32(58).string(message.denom);
    }
    if (message.distributionIntervalBlocks !== 0) {
      writer.uint32(64).uint64(message.distributionIntervalBlocks);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Params {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.txTaxRate = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.initialRewardPerBlockLumn = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.halvingIntervalBlocks = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.supplyCapLumn = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.decimals = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.minSendUlmn = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.denom = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.distributionIntervalBlocks = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      txTaxRate: isSet(object.txTaxRate)
        ? globalThis.String(object.txTaxRate)
        : isSet(object.tx_tax_rate)
        ? globalThis.String(object.tx_tax_rate)
        : "",
      initialRewardPerBlockLumn: isSet(object.initialRewardPerBlockLumn)
        ? globalThis.Number(object.initialRewardPerBlockLumn)
        : isSet(object.initial_reward_per_block_lumn)
        ? globalThis.Number(object.initial_reward_per_block_lumn)
        : 0,
      halvingIntervalBlocks: isSet(object.halvingIntervalBlocks)
        ? globalThis.Number(object.halvingIntervalBlocks)
        : isSet(object.halving_interval_blocks)
        ? globalThis.Number(object.halving_interval_blocks)
        : 0,
      supplyCapLumn: isSet(object.supplyCapLumn)
        ? globalThis.Number(object.supplyCapLumn)
        : isSet(object.supply_cap_lumn)
        ? globalThis.Number(object.supply_cap_lumn)
        : 0,
      decimals: isSet(object.decimals) ? globalThis.Number(object.decimals) : 0,
      minSendUlmn: isSet(object.minSendUlmn)
        ? globalThis.Number(object.minSendUlmn)
        : isSet(object.min_send_ulmn)
        ? globalThis.Number(object.min_send_ulmn)
        : 0,
      denom: isSet(object.denom) ? globalThis.String(object.denom) : "",
      distributionIntervalBlocks: isSet(object.distributionIntervalBlocks)
        ? globalThis.Number(object.distributionIntervalBlocks)
        : isSet(object.distribution_interval_blocks)
        ? globalThis.Number(object.distribution_interval_blocks)
        : 0,
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (message.txTaxRate !== "") {
      obj.txTaxRate = message.txTaxRate;
    }
    if (message.initialRewardPerBlockLumn !== 0) {
      obj.initialRewardPerBlockLumn = Math.round(message.initialRewardPerBlockLumn);
    }
    if (message.halvingIntervalBlocks !== 0) {
      obj.halvingIntervalBlocks = Math.round(message.halvingIntervalBlocks);
    }
    if (message.supplyCapLumn !== 0) {
      obj.supplyCapLumn = Math.round(message.supplyCapLumn);
    }
    if (message.decimals !== 0) {
      obj.decimals = Math.round(message.decimals);
    }
    if (message.minSendUlmn !== 0) {
      obj.minSendUlmn = Math.round(message.minSendUlmn);
    }
    if (message.denom !== "") {
      obj.denom = message.denom;
    }
    if (message.distributionIntervalBlocks !== 0) {
      obj.distributionIntervalBlocks = Math.round(message.distributionIntervalBlocks);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Params>, I>>(base?: I): Params {
    return Params.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Params>, I>>(object: I): Params {
    const message = createBaseParams();
    message.txTaxRate = object.txTaxRate ?? "";
    message.initialRewardPerBlockLumn = object.initialRewardPerBlockLumn ?? 0;
    message.halvingIntervalBlocks = object.halvingIntervalBlocks ?? 0;
    message.supplyCapLumn = object.supplyCapLumn ?? 0;
    message.decimals = object.decimals ?? 0;
    message.minSendUlmn = object.minSendUlmn ?? 0;
    message.denom = object.denom ?? "";
    message.distributionIntervalBlocks = object.distributionIntervalBlocks ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
