// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: lumen/tokenomics/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";

export const protobufPackage = "lumen.tokenomics.v1";

export interface MsgUpdateParams {
  authority: string;
  params: Params | undefined;
}

export interface MsgUpdateParamsResponse {
}

export interface MsgUpdateSlashingDowntimeParams {
  authority: string;
  /**
   * slash_fraction_downtime is the desired new downtime slashing fraction,
   * encoded as a decimal string, e.g. "0.01" for 1%.
   */
  slashFractionDowntime: string;
  /**
   * downtime_jail_duration is the desired jail duration for downtime,
   * expressed as a Go duration string, e.g. "600s" or "1h".
   */
  downtimeJailDuration: string;
}

export interface MsgUpdateSlashingDowntimeParamsResponse {
}

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

function createBaseMsgUpdateSlashingDowntimeParams(): MsgUpdateSlashingDowntimeParams {
  return { authority: "", slashFractionDowntime: "", downtimeJailDuration: "" };
}

export const MsgUpdateSlashingDowntimeParams: MessageFns<MsgUpdateSlashingDowntimeParams> = {
  encode(message: MsgUpdateSlashingDowntimeParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.slashFractionDowntime !== "") {
      writer.uint32(18).string(message.slashFractionDowntime);
    }
    if (message.downtimeJailDuration !== "") {
      writer.uint32(26).string(message.downtimeJailDuration);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateSlashingDowntimeParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateSlashingDowntimeParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.slashFractionDowntime = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.downtimeJailDuration = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateSlashingDowntimeParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      slashFractionDowntime: isSet(object.slashFractionDowntime) ? globalThis.String(object.slashFractionDowntime) : "",
      downtimeJailDuration: isSet(object.downtimeJailDuration) ? globalThis.String(object.downtimeJailDuration) : "",
    };
  },

  toJSON(message: MsgUpdateSlashingDowntimeParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.slashFractionDowntime !== "") {
      obj.slashFractionDowntime = message.slashFractionDowntime;
    }
    if (message.downtimeJailDuration !== "") {
      obj.downtimeJailDuration = message.downtimeJailDuration;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateSlashingDowntimeParams>, I>>(base?: I): MsgUpdateSlashingDowntimeParams {
    return MsgUpdateSlashingDowntimeParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateSlashingDowntimeParams>, I>>(
    object: I,
  ): MsgUpdateSlashingDowntimeParams {
    const message = createBaseMsgUpdateSlashingDowntimeParams();
    message.authority = object.authority ?? "";
    message.slashFractionDowntime = object.slashFractionDowntime ?? "";
    message.downtimeJailDuration = object.downtimeJailDuration ?? "";
    return message;
  },
};

function createBaseMsgUpdateSlashingDowntimeParamsResponse(): MsgUpdateSlashingDowntimeParamsResponse {
  return {};
}

export const MsgUpdateSlashingDowntimeParamsResponse: MessageFns<MsgUpdateSlashingDowntimeParamsResponse> = {
  encode(_: MsgUpdateSlashingDowntimeParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateSlashingDowntimeParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateSlashingDowntimeParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateSlashingDowntimeParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateSlashingDowntimeParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateSlashingDowntimeParamsResponse>, I>>(
    base?: I,
  ): MsgUpdateSlashingDowntimeParamsResponse {
    return MsgUpdateSlashingDowntimeParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateSlashingDowntimeParamsResponse>, I>>(
    _: I,
  ): MsgUpdateSlashingDowntimeParamsResponse {
    const message = createBaseMsgUpdateSlashingDowntimeParamsResponse();
    return message;
  },
};

export interface Msg {
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse>;
  UpdateSlashingDowntimeParams(
    request: MsgUpdateSlashingDowntimeParams,
  ): Promise<MsgUpdateSlashingDowntimeParamsResponse>;
}

export const MsgServiceName = "lumen.tokenomics.v1.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.UpdateParams = this.UpdateParams.bind(this);
    this.UpdateSlashingDowntimeParams = this.UpdateSlashingDowntimeParams.bind(this);
  }
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse> {
    const data = MsgUpdateParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateParams", data);
    return promise.then((data) => MsgUpdateParamsResponse.decode(new BinaryReader(data)));
  }

  UpdateSlashingDowntimeParams(
    request: MsgUpdateSlashingDowntimeParams,
  ): Promise<MsgUpdateSlashingDowntimeParamsResponse> {
    const data = MsgUpdateSlashingDowntimeParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateSlashingDowntimeParams", data);
    return promise.then((data) => MsgUpdateSlashingDowntimeParamsResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
