// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               unknown
// source: lumen/pqc/v1/params.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Coin } from "../../../cosmos/base/v1beta1/coin";

export const protobufPackage = "lumen.pqc.v1";

export enum PqcPolicy {
  PQC_POLICY_DISABLED = 0,
  PQC_POLICY_OPTIONAL = 1,
  PQC_POLICY_REQUIRED = 2,
  UNRECOGNIZED = -1,
}

export function pqcPolicyFromJSON(object: any): PqcPolicy {
  switch (object) {
    case 0:
    case "PQC_POLICY_DISABLED":
      return PqcPolicy.PQC_POLICY_DISABLED;
    case 1:
    case "PQC_POLICY_OPTIONAL":
      return PqcPolicy.PQC_POLICY_OPTIONAL;
    case 2:
    case "PQC_POLICY_REQUIRED":
      return PqcPolicy.PQC_POLICY_REQUIRED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PqcPolicy.UNRECOGNIZED;
  }
}

export function pqcPolicyToJSON(object: PqcPolicy): string {
  switch (object) {
    case PqcPolicy.PQC_POLICY_DISABLED:
      return "PQC_POLICY_DISABLED";
    case PqcPolicy.PQC_POLICY_OPTIONAL:
      return "PQC_POLICY_OPTIONAL";
    case PqcPolicy.PQC_POLICY_REQUIRED:
      return "PQC_POLICY_REQUIRED";
    case PqcPolicy.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Params {
  policy: PqcPolicy;
  minScheme: string;
  minBalanceForLink: Coin | undefined;
  powDifficultyBits: number;
}

function createBaseParams(): Params {
  return { policy: 0, minScheme: "", minBalanceForLink: undefined, powDifficultyBits: 0 };
}

export const Params: MessageFns<Params> = {
  encode(message: Params, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.policy !== 0) {
      writer.uint32(8).int32(message.policy);
    }
    if (message.minScheme !== "") {
      writer.uint32(26).string(message.minScheme);
    }
    if (message.minBalanceForLink !== undefined) {
      Coin.encode(message.minBalanceForLink, writer.uint32(42).fork()).join();
    }
    if (message.powDifficultyBits !== 0) {
      writer.uint32(48).uint32(message.powDifficultyBits);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Params {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.policy = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.minScheme = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.minBalanceForLink = Coin.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.powDifficultyBits = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      policy: isSet(object.policy) ? pqcPolicyFromJSON(object.policy) : 0,
      minScheme: isSet(object.minScheme)
        ? globalThis.String(object.minScheme)
        : isSet(object.min_scheme)
        ? globalThis.String(object.min_scheme)
        : "",
      minBalanceForLink: isSet(object.minBalanceForLink)
        ? Coin.fromJSON(object.minBalanceForLink)
        : isSet(object.min_balance_for_link)
        ? Coin.fromJSON(object.min_balance_for_link)
        : undefined,
      powDifficultyBits: isSet(object.powDifficultyBits)
        ? globalThis.Number(object.powDifficultyBits)
        : isSet(object.pow_difficulty_bits)
        ? globalThis.Number(object.pow_difficulty_bits)
        : 0,
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (message.policy !== 0) {
      obj.policy = pqcPolicyToJSON(message.policy);
    }
    if (message.minScheme !== "") {
      obj.minScheme = message.minScheme;
    }
    if (message.minBalanceForLink !== undefined) {
      obj.minBalanceForLink = Coin.toJSON(message.minBalanceForLink);
    }
    if (message.powDifficultyBits !== 0) {
      obj.powDifficultyBits = Math.round(message.powDifficultyBits);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Params>, I>>(base?: I): Params {
    return Params.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Params>, I>>(object: I): Params {
    const message = createBaseParams();
    message.policy = object.policy ?? 0;
    message.minScheme = object.minScheme ?? "";
    message.minBalanceForLink = (object.minBalanceForLink !== undefined && object.minBalanceForLink !== null)
      ? Coin.fromPartial(object.minBalanceForLink)
      : undefined;
    message.powDifficultyBits = object.powDifficultyBits ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
