// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: lumen/pqc/v1/pqc.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "lumen.pqc.v1";

export interface AccountPQC {
  addr: string;
  scheme: string;
  pubKey: Uint8Array;
  addedAt: number;
}

export interface PQCSignatureEntry {
  addr: string;
  scheme: string;
  signature: Uint8Array;
}

export interface PQCSignatures {
  signatures: PQCSignatureEntry[];
}

function createBaseAccountPQC(): AccountPQC {
  return { addr: "", scheme: "", pubKey: new Uint8Array(0), addedAt: 0 };
}

export const AccountPQC: MessageFns<AccountPQC> = {
  encode(message: AccountPQC, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.addr !== "") {
      writer.uint32(10).string(message.addr);
    }
    if (message.scheme !== "") {
      writer.uint32(18).string(message.scheme);
    }
    if (message.pubKey.length !== 0) {
      writer.uint32(26).bytes(message.pubKey);
    }
    if (message.addedAt !== 0) {
      writer.uint32(32).int64(message.addedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AccountPQC {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccountPQC();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.addr = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.scheme = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pubKey = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.addedAt = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AccountPQC {
    return {
      addr: isSet(object.addr) ? globalThis.String(object.addr) : "",
      scheme: isSet(object.scheme) ? globalThis.String(object.scheme) : "",
      pubKey: isSet(object.pubKey) ? bytesFromBase64(object.pubKey) : new Uint8Array(0),
      addedAt: isSet(object.addedAt) ? globalThis.Number(object.addedAt) : 0,
    };
  },

  toJSON(message: AccountPQC): unknown {
    const obj: any = {};
    if (message.addr !== "") {
      obj.addr = message.addr;
    }
    if (message.scheme !== "") {
      obj.scheme = message.scheme;
    }
    if (message.pubKey.length !== 0) {
      obj.pubKey = base64FromBytes(message.pubKey);
    }
    if (message.addedAt !== 0) {
      obj.addedAt = Math.round(message.addedAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AccountPQC>, I>>(base?: I): AccountPQC {
    return AccountPQC.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AccountPQC>, I>>(object: I): AccountPQC {
    const message = createBaseAccountPQC();
    message.addr = object.addr ?? "";
    message.scheme = object.scheme ?? "";
    message.pubKey = object.pubKey ?? new Uint8Array(0);
    message.addedAt = object.addedAt ?? 0;
    return message;
  },
};

function createBasePQCSignatureEntry(): PQCSignatureEntry {
  return { addr: "", scheme: "", signature: new Uint8Array(0) };
}

export const PQCSignatureEntry: MessageFns<PQCSignatureEntry> = {
  encode(message: PQCSignatureEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.addr !== "") {
      writer.uint32(10).string(message.addr);
    }
    if (message.scheme !== "") {
      writer.uint32(18).string(message.scheme);
    }
    if (message.signature.length !== 0) {
      writer.uint32(26).bytes(message.signature);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PQCSignatureEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePQCSignatureEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.addr = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.scheme = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.signature = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PQCSignatureEntry {
    return {
      addr: isSet(object.addr) ? globalThis.String(object.addr) : "",
      scheme: isSet(object.scheme) ? globalThis.String(object.scheme) : "",
      signature: isSet(object.signature) ? bytesFromBase64(object.signature) : new Uint8Array(0),
    };
  },

  toJSON(message: PQCSignatureEntry): unknown {
    const obj: any = {};
    if (message.addr !== "") {
      obj.addr = message.addr;
    }
    if (message.scheme !== "") {
      obj.scheme = message.scheme;
    }
    if (message.signature.length !== 0) {
      obj.signature = base64FromBytes(message.signature);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PQCSignatureEntry>, I>>(base?: I): PQCSignatureEntry {
    return PQCSignatureEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PQCSignatureEntry>, I>>(object: I): PQCSignatureEntry {
    const message = createBasePQCSignatureEntry();
    message.addr = object.addr ?? "";
    message.scheme = object.scheme ?? "";
    message.signature = object.signature ?? new Uint8Array(0);
    return message;
  },
};

function createBasePQCSignatures(): PQCSignatures {
  return { signatures: [] };
}

export const PQCSignatures: MessageFns<PQCSignatures> = {
  encode(message: PQCSignatures, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.signatures) {
      PQCSignatureEntry.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PQCSignatures {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePQCSignatures();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signatures.push(PQCSignatureEntry.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PQCSignatures {
    return {
      signatures: globalThis.Array.isArray(object?.signatures)
        ? object.signatures.map((e: any) => PQCSignatureEntry.fromJSON(e))
        : [],
    };
  },

  toJSON(message: PQCSignatures): unknown {
    const obj: any = {};
    if (message.signatures?.length) {
      obj.signatures = message.signatures.map((e) => PQCSignatureEntry.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PQCSignatures>, I>>(base?: I): PQCSignatures {
    return PQCSignatures.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PQCSignatures>, I>>(object: I): PQCSignatures {
    const message = createBasePQCSignatures();
    message.signatures = object.signatures?.map((e) => PQCSignatureEntry.fromPartial(e)) || [];
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
