// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               unknown
// source: lumen/pqc/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "lumen.pqc.v1";

export interface MsgLinkAccountPQC {
  creator: string;
  scheme: string;
  pubKey: Uint8Array;
  powNonce: Uint8Array;
}

export interface MsgLinkAccountPQCResponse {
}

function createBaseMsgLinkAccountPQC(): MsgLinkAccountPQC {
  return { creator: "", scheme: "", pubKey: new Uint8Array(0), powNonce: new Uint8Array(0) };
}

export const MsgLinkAccountPQC: MessageFns<MsgLinkAccountPQC> = {
  encode(message: MsgLinkAccountPQC, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.scheme !== "") {
      writer.uint32(18).string(message.scheme);
    }
    if (message.pubKey.length !== 0) {
      writer.uint32(26).bytes(message.pubKey);
    }
    if (message.powNonce.length !== 0) {
      writer.uint32(34).bytes(message.powNonce);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgLinkAccountPQC {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgLinkAccountPQC();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.scheme = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pubKey = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.powNonce = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgLinkAccountPQC {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      scheme: isSet(object.scheme) ? globalThis.String(object.scheme) : "",
      pubKey: isSet(object.pubKey)
        ? bytesFromBase64(object.pubKey)
        : isSet(object.pub_key)
        ? bytesFromBase64(object.pub_key)
        : new Uint8Array(0),
      powNonce: isSet(object.powNonce)
        ? bytesFromBase64(object.powNonce)
        : isSet(object.pow_nonce)
        ? bytesFromBase64(object.pow_nonce)
        : new Uint8Array(0),
    };
  },

  toJSON(message: MsgLinkAccountPQC): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.scheme !== "") {
      obj.scheme = message.scheme;
    }
    if (message.pubKey.length !== 0) {
      obj.pubKey = base64FromBytes(message.pubKey);
    }
    if (message.powNonce.length !== 0) {
      obj.powNonce = base64FromBytes(message.powNonce);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgLinkAccountPQC>, I>>(base?: I): MsgLinkAccountPQC {
    return MsgLinkAccountPQC.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgLinkAccountPQC>, I>>(object: I): MsgLinkAccountPQC {
    const message = createBaseMsgLinkAccountPQC();
    message.creator = object.creator ?? "";
    message.scheme = object.scheme ?? "";
    message.pubKey = object.pubKey ?? new Uint8Array(0);
    message.powNonce = object.powNonce ?? new Uint8Array(0);
    return message;
  },
};

function createBaseMsgLinkAccountPQCResponse(): MsgLinkAccountPQCResponse {
  return {};
}

export const MsgLinkAccountPQCResponse: MessageFns<MsgLinkAccountPQCResponse> = {
  encode(_: MsgLinkAccountPQCResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgLinkAccountPQCResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgLinkAccountPQCResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgLinkAccountPQCResponse {
    return {};
  },

  toJSON(_: MsgLinkAccountPQCResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgLinkAccountPQCResponse>, I>>(base?: I): MsgLinkAccountPQCResponse {
    return MsgLinkAccountPQCResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgLinkAccountPQCResponse>, I>>(_: I): MsgLinkAccountPQCResponse {
    const message = createBaseMsgLinkAccountPQCResponse();
    return message;
  },
};

export interface Msg {
  LinkAccountPQC(request: MsgLinkAccountPQC): Promise<MsgLinkAccountPQCResponse>;
}

export const MsgServiceName = "lumen.pqc.v1.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.LinkAccountPQC = this.LinkAccountPQC.bind(this);
  }
  LinkAccountPQC(request: MsgLinkAccountPQC): Promise<MsgLinkAccountPQCResponse> {
    const data = MsgLinkAccountPQC.encode(request).finish();
    const promise = this.rpc.request(this.service, "LinkAccountPQC", data);
    return promise.then((data) => MsgLinkAccountPQCResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
